#' Loading Input data.
#'
#' @import Matrix
#' @import dplyr
#' @importFrom foreach foreach %dopar%
#' @importFrom BSgenome getBSgenome
#' @importFrom data.table := .N
#' @param modkit_file 
#' Path to the TSV file generated by `modkit extract calls` for Oxford Nanopore Technology data and Biomodal 6-base data.  
#' The file must contain the per-base modified base calls for each read, 
#' including reference position, strand, call code (e.g. m/h/-), call probability,
#' and other metadata exported by modkit.
#' @param bismark_file 
#' Path to one of the TXT files generated by `bismark_methylation_extractor` for
#' BISMARK-aligned BS-seq data and DRAGEN-aligned 5-base data.  
#' The file must contain the per-base modified base calls for each read, 
#' including strand, chromosome, reference position and call code (i.e. z/h/x and Z/H/X).
#' @param read_coord_bedfile 
#' Path to a BED file containing genomic alignment coordinates for each read.  
#' Typically generated with:
#' `samtools view -b <bam> | bedtools bamtobed`.  
#' The file must include at least 6 columns (chr, start, end, readID, score, strand).
#' @param cpg_file Optional character string. Path to a CpG coordinate file.
#' The file should contain at least two columns: chromosome and CpG position.
#' If `NULL`, CpG coordinates are extracted from the genome using
#' `genome_fasta` or `genome_assembly`.
#' @param mod_file_1based
#' Logical value indicating whether genomic positions in `modkit_file` or `bismark_file` are
#' already reported using 1-based coordinates.
#' If `FALSE`, positions are assumed to be 0-based and are internally converted
#' to 1-based coordinates before downstream processing. (Default: FALSE)
#' @param read_coord_1based
#' Logical value indicating whether the read alignment coordinates in
#' `read_coord_bedfile` are already reported using 1-based coordinates.
#' If `FALSE`, coordinates are assumed to follow the standard BED convention
#' with 0-based start positions and are internally converted when needed. (Default: FALSE)
#' @param cpg_file_1based Logical. Whether CpG positions in `cpg_file` are
#' already 1-based. If `FALSE`, 1 is added to the CpG position column.
#' Default is `TRUE`.
#' @param region_file_1based Logical. Whether the region file already uses
#' 1-based inclusive coordinates. If `FALSE`, regions are interpreted as
#' BED-like 0-based half-open intervals and the start coordinate is converted by
#' adding 1. Default is `FALSE`.
#' @param read_coords_gr Logical value to return a GRanges object of the loaded read_coord_bedfile (default: FALSE).
#' @param region_file
#' Optional path to a BED-like file containing genomic regions to restrict the
#' analysis to.
#' If provided, only reads and methylation calls overlapping these regions are
#' retained.
#' The file should contain at least three columns: chromosome, start and end.
#' Additional columns are allowed but not required.
#' If `NULL`, the analysis is performed genome-wide or on the chromosomes
#' specified by the user.
#' @param merge_regions
#' Logical value indicating whether overlapping or adjacent regions in
#' `region_file` should be merged before extracting methylation calls.
#' If `TRUE`, regions are reduced to a non-overlapping set of intervals.
#' This is useful to avoid duplicated counting of reads or target base sites falling
#' within overlapping regions.
#' If `FALSE`, regions are used as provided. (Default: TRUE)
#' @param genome_fasta Path to the genome fasta file.
#' @param genome_assembly 
#' A genome reference used to extract target base positions and check reference bases.  
#' Accepted values:  
#' - a **BSgenome object**,  
#' - the full package name of an installed BSgenome (e.g. `"BSgenome.Hsapiens.UCSC.hg38"`),  
#' - an **NCBI assembly name** (e.g. `"GRCh38"`),  
#' - a **UCSC assembly name** (e.g. `"hg38"`, `"mm10"`).  
#' If a character string is provided, the function attempts to load the 
#' corresponding BSgenome package automatically.
#' @param install_if_missing  Boolean value. When set to TRUE, if the BSgenome 
#' provided with `genome_assembly` is not present, it will be installed. Default value: FALSE.
#' @param sel_chr 
#' Optional character vector specifying one or more chromosomes to include  
#' (e.g. `"chr21"` or `c("chr21", "chr22")`).  
#' If `NULL`, all chromosomes present in both input files are processed.
#' @param bases 
#' Character vector specifying which dinucleotide(s) or motif(s) to analyze.  
#' Default `"CG"` identifies target base sites for 5mC/5hmC calling.  
#' Other motifs (e.g. `"CA"`, `"CT"`) can be used for alternative base modifications 
#' if present in the provided modification file (`modkit_file` or `bismark_file`).
#' @param mapq_th 
#' Mapping quality threshold.  
#' Only reads with mapping quality >= `mapq_th` (from the BED column 5 or BAM MAPQ)  
#' are included.  
#' Default `0` keeps all reads.
#' @param base_qual_th 
#' Minimum base calling quality threshold for including a modified base.  
#' Corresponds to the `base_qual` column from `modkit extract calls`.  
#' Default `0` keeps all base calls.
#' @param base_map_qual_th 
#' Minimum base calling quality threshold for including a mutated base. 
#' Default `0` keeps all base calls.
#' @param output_type Character string specifying the output type. One of:
#' \itemize{
#'   \item `"mhap"`: return a lightweight mHap object only.
#'   \item `"sparse"`: build and return a read-by-CpG sparse matrix only.
#'   \item `"both"`: return both the mHap object and the sparse matrix.
#' }
#' @param output_file 
#' Optional path to save the generated list object (RDS format).  
#' If `NULL`, the object is only returned in memory.
#' @param code_map Named numeric vector that maps `call_code` values
#'   from the modkit/bismark output to integer codes used in the matrix.
#'   Names must correspond to possible values of the `call_code` column.
#'   A special name `"default"` can be provided and is used for any `call_code` that is not
#'   explicitly listed in `code_map`. For example:
#'   `code_map = c(default = 1L, '-' = 2L, 'z' = 2L, m = 3L, 'Z' = 3L, h = 4L)` will assign:
#'   - 2 to `call_code == "-"` in `modkit_file` or `call_code == "z"` in `bismark_file`
#'   - 3 to `call_code == "m"` in `modkit_file` or `call_code == "Z"` in `bismark_file`
#'   - 4 to `call_code == "h"` in `modkit_file`
#'   - 1 to all other codes.
#'   Values are stored as signed integers; if `ref_strand == "-"`,
#'   the value is multiplied by -1.
#' @param code_map_epiallele 
#' Named integer vector defining how the sparse matrix values (e.g. 1, 2, 3) 
#' should be converted into binary epialleles (e.g. unmethylated = 0, methylated = 1).
#' @param remove_ambiguous 
#' Logical value indicating whether rows containing ambiguous or unresolved 
#' epiallele codes should be removed from the epiallele matrix. 
#' If `TRUE`, all rows in `epi_mat` containing at least one value included 
#' in `unknown_code` are discarded. If `FALSE`, no filtering based on ambiguous 
#' codes is applied. Default is `TRUE`.
#' @param unknown_code 
#' Numeric vector specifying the code values that should be considered ambiguous, 
#' unresolved, or unknown. These values are used only when `remove_ambiguous = TRUE`. 
#' Any row of `epi_mat` containing at least one value present in 
#' `unknown_code` will be removed. Default is `c(2)`.
#' @param min_cpg_per_read Integer. Minimum number of CpG sites required for a
#'   read or fragment to be retained in the mHap output.
#' @param add_map_id Logical. Whether to include a \code{map_id} column as the
#'   seventh column of the written mHap file. The \code{map_id} links each
#'   collapsed mHap record to the original read identifiers reported in the
#'   read-map table. Default is \code{TRUE}.
#' @param return_read_map Logical. Whether to generate and return a
#'   \code{map_id}/\code{read_id} table linking each collapsed mHap record to
#'   the original reads or fragments that contributed to it. Default is
#'   \code{TRUE}.
#' @param handle_missing_cpg Character string indicating how missing CpG calls
#'   should be handled during mHap object generation. Three options are
#'   available:
#'   \describe{
#'     \item{\code{"drop"}}{Discard reads or fragments with missing CpG calls
#'       within the reference CpG span used to build the haplotype.}
#'     \item{\code{"unknown"}}{Retain reads or fragments and encode missing
#'       CpG calls using \code{missing_code}.}
#'     \item{\code{"split"}}{Split each read or fragment into consecutive
#'       haplotype blocks upstream and downstream of missing CpG calls, so that
#'       only contiguous observed CpG blocks are retained.}
#'   }
#' @param rm_zero_col Boolean value. When set to TRUE, zero columns are filtered out. Default value: FALSE.
#' @param nThread Number of threads used by data.table::fread() to load modkit_file/bismark_file and read_coord_bedfile.
#' @param parallel
#' Logical value indicating whether the sparse matrix construction should be parallelized.
#' If `TRUE`, genomic motif positions are partitioned into genomic chunks and
#' each chunk is processed independently in parallel before being combined into
#' the final sparse matrix. If `FALSE`, the sparse matrix is built sequentially. (Default: `TRUE`)
#' @param n_workers
#' Integer specifying the number of parallel workers used during sparse matrix
#' construction when `parallel = TRUE`.
#' Each worker processes one genomic chunk at a time using a `foreach`
#' parallel backend. (Default: `4`)
#' @param chunks_per_core
#' Integer specifying how many genomic chunks are created for each parallel
#' worker during sparse matrix construction.
#' The total number of chunks is approximately `n_workers × chunks_per_core`.
#' Increasing this value generally improves load balancing, especially when
#' genomic regions differ substantially in target sites density or read coverage,
#' at the cost of a small increase in scheduling overhead. (Default: `10`) 
#' @details
#' When `parallel = TRUE`, the sparse matrix is constructed using a genomic
#' chunking strategy. CpG positions are partitioned into multiple genomic
#' chunks, and for each chunk only the overlapping reads and modification calls
#' are processed. This substantially reduces memory usage compared with
#' distributing the complete input tables to each worker while maintaining the
#' same final sparse matrix.
#' @return A list containing the sparse matrix (Matrix::dgCMatrix),
#'   with reads in rows and target base positions in columns, and a GRanges object of the read mapping coordinates.
#'   The latter is return only if `read_coords_gr = TRUE` and can be used .
#' @export


loadInputFromModFile <- function(
    modkit_file = NULL,
    bismark_file = NULL,
    read_coord_bedfile = NULL,
    cpg_file = NULL,
    region_file = NULL,
    # mut_file = NULL,
    
    mod_file_1based=FALSE,
    read_coord_1based=FALSE,
    cpg_file_1based = TRUE,
    region_file_1based = FALSE,
    # mut_file_1based = FALSE,
    
    read_coords_gr = FALSE,
    merge_regions = TRUE,
    genome_fasta = NULL,
    genome_assembly = 'hg38',
    sel_chr = NULL,
    bases = "CG",
    
    mapq_th = 0,
    base_qual_th = 0,
    base_map_qual_th = 0,
    
    output_type = c("mhap", "sparse", "both"),
    output_file = NULL,
    
    code_map = c(default = 1L, 
                 '-' = 2L, 'z' = 2L, 
                 m = 3L,   'Z' = 3L, 
                 h = 4L
    ),
    code_map_epiallele = c(`1`= 2, `2` = 0, `3`= 1, `4`= 0),
    # mut_code_map = c("C_T" = 5L, "C_G" = 6L, "C_A" = 7L),
    
    unknown_code = c(2),
    remove_ambiguous = FALSE,
    min_cpg_per_read = 1L,
    add_map_id = TRUE,
    return_read_map = TRUE,
    handle_missing_cpg = c("drop", "unknown", "split"),
    
    rm_zero_col = FALSE,
    nThread = 8,
    install_if_missing = FALSE,
    parallel = TRUE,
    n_workers = 4,
    chunks_per_core = 10
) {
  
  output_type <- match.arg(output_type)
  
  check_mod_files(modkit_file, bismark_file)
  check_bases(bases)
  check_code_map(code_map)
  
  message("Loading mod file...")
  mod_df <- load_mod_calls(
    modkit_file = modkit_file,
    bismark_file = bismark_file,
    mod_file_1based = mod_file_1based,
    base_qual_th = base_qual_th,
    sel_chr = sel_chr,
    code_map = code_map,
    nThread = nThread
  )
  
  regions_gr <- NULL
  
  if (!is.null(region_file) && !region_file %in% c("", "NA", "NULL", "null", "None", "none")) {
    
    message("Loading regions: ", region_file)
    
    regions_gr <- load_regions_bed(
      region_file = region_file,
      sel_chr = sel_chr,
      merge_regions = merge_regions,
      region_file_1based = region_file_1based,
      nThread = nThread
    )
    
    # message("Filtering mmod file records by regions...")
    # mod_df <- filter_mod_by_regions(
    #   mod_df = mod_df,
    #   regions_gr = regions_gr
    # )
    # if (nrow(mod_df) == 0L) {
    #   stop("No mHap records remain after region filtering.")
    # }
  }
  
  
  message("Loading CpG coordinates...")
  if (!is.null(cpg_file)) {
    
    cpg_df_all <- load_cpg_file(
      cpg_file = cpg_file,
      cpg_file_1based = cpg_file_1based,
      sel_chr = sel_chr,
      nThread = nThread
    )
    
  } else {
    
    genome <- load_genome(
      genome_assembly = genome_assembly,
      sel_chr = sel_chr,
      genome_fasta = genome_fasta,
      install_if_missing = install_if_missing
    )
    
    cpg_df_all <- get_coordinates(
      genome = genome,
      bases = bases,
      sel_chr = sel_chr,
      regions = NULL,
      nThread = nThread
    )
    
    cpg_df_all <- normalize_cpg_df(cpg_df_all)
  }
  
  if (nrow(cpg_df_all) == 0L) {
    stop("No CpG coordinates available.")
  }
  
  
  if (!is.null(regions_gr)) {
    message("Filtering CpG coordinates by regions...")
    cpg_df_target <- filter_cpg_by_regions(
      cpg_df = cpg_df_all,
      regions_gr = regions_gr
    )
  } else {
    cpg_df_target <- cpg_df_all
  }
  
  if (nrow(cpg_df_target) == 0L) {
    stop("No target CpG coordinates remain after region filtering.")
  }
  
  
  sparse_matrix <- NULL
  read_gr <- NULL
  mhap_from_modFile <- NULL
  
  
  if (output_type %in%  c("sparse", "both")) {
    
    read_coords_df <- load_read_coords(
      read_coord_bedfile = read_coord_bedfile,
      read_coord_1based = read_coord_1based,
      mapq_th = mapq_th,
      sel_chr = sel_chr,
      nThread = nThread
    )
    
    if (read_coords_gr) {
      read_gr <- GenomicRanges::GRanges(
        seqnames = read_coords_df$chr,
        ranges = IRanges::IRanges(
          start = read_coords_df$start,
          end = read_coords_df$end
        )
      )
    } else {
      read_gr <- NULL
    }
    
    check_consistency(read_coords_df, mod_df, cpg_df_target)
    
    if (parallel) {
      mat_base <- build_sparse_matrix_parallel_chunks(
        base_coords_df = cpg_df_target,
        read_coords_df = read_coords_df,
        mod_df = mod_df,
        cores = n_workers,
        chunks_per_core = chunks_per_core
      )
    } else {
      mat_base <- build_sparse_matrix(
        base_coords_df = cpg_df_target,
        read_coords_df = read_coords_df,
        mod_df = mod_df
      )
    }
    
    sparse_matrix <- filter_matrix(mat_base, rm_zero_col = rm_zero_col)
    
    # if (!is.null(mut_file)){
    #   mut_df <- load_mut_calls(
    #     mut_file = mut_file,
    #     base_qual_th = base_qual_th,
    #     base_map_qual_th = base_map_qual_th,
    #     sel_chr = sel_chr,
    #     mut_code_map = mut_code_map, 
    #     nThread = nThread
    #   )
    #   
    #   sparse_matrix <- add_mut_to_sparseMat(sparse_matrix, mut_df)
    # }
    
  }
  
  mhap_obj <- NULL
  
  if (output_type %in% c("mhap", "both")) {
    
    res_mhap <- modDfToMhap(
      mod_df = mod_df,
      cpg_df = cpg_df_all,
      code_map_epiallele = code_map_epiallele,
      handle_missing_cpg = handle_missing_cpg,
      remove_ambiguous = remove_ambiguous,
      unknown_code = unknown_code,
      min_cpg_per_read = min_cpg_per_read,
      add_map_id = add_map_id,
      return_read_map = return_read_map,
      parallel = parallel,
      n_workers = n_workers,
      chunks_per_core = chunks_per_core
    )
    
    mhap_df <- res_mhap$mhap
    read_map_df <- res_mhap$read_map
    
    mhap_obj <- list(
      mhap = mhap_df,
      cpg_df = cpg_df_target,
      cpg_df_all = cpg_df_all,
      read_map_df = read_map_df,
      regions = regions_gr,
      backend = "mhap"
    )
  }
  
  res <- list(
    sparse_matrix = sparse_matrix,
    read_coord_gr = read_gr,
    mhap_obj = mhap_obj
  )
  
  if (!is.null(output_file)) {
    message("Saving output object to: ", output_file)
    saveRDS(res, output_file)
  }
  
  message("Completed!")
  
  return(res)
}


# ---- Helpers ----

check_mod_files <- function(modkit_file, bismark_file) {
  if ((is.null(modkit_file) & is.null(bismark_file)) | (!is.null(modkit_file) & !is.null(bismark_file))) {
    stop("You must provide only one file with per read modification calls using either `modkit_file` or `bismark_file` argument.")
  }
}


check_bases <- function(bases) {
  if (length(bases) != 1L) {
    stop("`bases` must be a single string (e.g. 'CG').")
  }
}


check_code_map <- function(code_map) {
  code_map <- unlist(code_map)
  if (!("default" %in% names(code_map))) {
    stop("code_map must include a 'default' entry")
  }
  if (any(code_map == 0L)) {
    stop("code_map cannot contain 0. Sparse matrices treat 0 as 'no information'.")
  }
  if (any(code_map < 0L)) {
    stop("code_map cannot contain negative values. Negative strand values are assigned automatically.")
  }
  if (!is.numeric(code_map)) {
    stop("`code_map` must be a named numeric vector or list coercible to numeric.")
  }
}


check_consistency <- function(read_coords_df, mod_df, base_coords_df){
  
  message("Running consistency checks...")
  
  ## ---- 2. Chromosomes present in input files ----
  chr_bed <- unique(read_coords_df$chr)
  chr_mod <- unique(mod_df$chr)
  chr_ref <- unique(base_coords_df$chr)
  
  common_chr <- Reduce(intersect, list(chr_bed, chr_mod, chr_ref))
  
  if (length(common_chr) == 0L) {
    stop("No chromosomes in common among BED, modkit, and genome coordinates.")
  }
  
  cat("Common chromosomes between inputs: ", paste(common_chr, collapse = ", "), '\n')
  
  ## ---- 3. Read ID consistency ----
  readIDs_no_mateDiff = stringr::str_remove(read_coords_df$readID, '/2|/1')
  missing_in_mod <- base::setdiff(readIDs_no_mateDiff, mod_df$read_id)
  missing_in_bed    <- base::setdiff(mod_df$read_id, readIDs_no_mateDiff)
  
  if (length(missing_in_mod) > 0L) {
    message("[WARN] Reads present in BED but not in mod file: ", 
            length(missing_in_mod))
  }
  
  if (length(missing_in_bed) > 0L) {
    stop("Some reads present in the mod file do not exist in BED: ",
         paste(head(missing_in_bed), collapse = ", "), " ...")
  }
  
  ## ---- 4. Positions of motifs ----
  if (nrow(base_coords_df) == 0L) {
    stop("No motif coordinates (e.g., CG) extracted from genome.")
  }
  
  ## ---- 5. Checks passed ----
  cat("Consistency checks passed.\n")
  return(invisible(TRUE))
}


get_base_positions <- function(seq, bases = "CG") {
  seq <- as.character(seq)
  starts <- unlist(gregexpr(bases, seq, fixed = TRUE))
  starts <- starts[starts > 0]
  return(starts)
}


get_coordinates <- function(
    genome,
    bases = "CG",
    sel_chr = NULL,
    regions = NULL,
    nThread = 1
) {
  
  message("Extracting positions of ", bases, " in the reference genome...")
  
  chromosomes <- names(genome)
  
  if (!is.null(sel_chr)) {
    chromosomes <- chromosomes[chromosomes %in% sel_chr]
  }
  
  if (length(chromosomes) == 0L) {
    stop("No chromosomes available for coordinate extraction.")
  }
  
  if (is.null(regions)) {
    
    message("No BED regions provided. Extracting motifs from full chromosomes.")
    
    if (nThread > 1L) {
      cl <- parallel::makeCluster(nThread)
      on.exit(parallel::stopCluster(cl), add = TRUE)
      
      base_genome <- parallel::parLapply(
        cl,
        chromosomes,
        function(chr, genome, bases) {
          hits <- Biostrings::matchPattern(bases, genome[[chr]], fixed = TRUE)
          if (length(hits) == 0L) return(NULL)
          
          data.frame(
            chr = chr,
            pos = BiocGenerics::start(hits)
          )
        },
        genome = genome,
        bases = bases
      )
      
    } else {
      
      base_genome <- lapply(chromosomes, function(chr) {
        hits <- Biostrings::matchPattern(bases, genome[[chr]], fixed = TRUE)
        if (length(hits) == 0L) return(NULL)
        
        data.frame(
          chr = chr,
          pos = BiocGenerics::start(hits)
        )
      })
    }
    
  } else {
    
    regions <- GenomeInfoDb::keepSeqlevels(
      regions,
      value = base::intersect(GenomeInfoDb::seqlevels(regions), chromosomes),
      pruning.mode = "coarse"
    )
    
    regions <- regions[GenomicRanges::seqnames(regions) %in% chromosomes]
    
    if (length(regions) == 0L) {
      stop("No regions remain after chromosome filtering.", call. = FALSE)
    }
    
    if (nThread > 1L) {
      
      region_idx <- split(
        seq_along(regions),
        cut(seq_along(regions), breaks = nThread, labels = FALSE)
      )
      
      cl <- parallel::makeCluster(nThread)
      on.exit(parallel::stopCluster(cl), add = TRUE)
      
      base_genome <- parallel::parLapply(
        cl,
        region_idx,
        function(idx, genome, regions, bases) {
          
          out <- lapply(idx, function(i) {
            chr <- as.character(GenomicRanges::seqnames(regions)[i])
            start_i <- GenomicRanges::start(regions)[i]
            end_i <- GenomicRanges::end(regions)[i]
            
            seq_i <- Biostrings::subseq(
              genome[[chr]],
              start = start_i,
              end = end_i
            )
            
            hits <- Biostrings::matchPattern(
              bases,
              seq_i,
              fixed = TRUE
            )
            
            if (length(hits) == 0L) return(NULL)
            
            data.frame(
              chr = chr,
              pos = start_i + BiocGenerics::start(hits) - 1L
            )
          })
          
          do.call(rbind, out)
        },
        genome = genome,
        regions = regions,
        bases = bases
      )
      
    } else {
      
      base_genome <- lapply(seq_along(regions), function(i) {
        chr <- as.character(GenomicRanges::seqnames(regions)[i])
        start_i <- GenomicRanges::start(regions)[i]
        end_i <- GenomicRanges::end(regions)[i]
        
        seq_i <- Biostrings::subseq(
          genome[[chr]],
          start = start_i,
          end = end_i
        )
        
        hits <- Biostrings::matchPattern(
          bases,
          seq_i,
          fixed = TRUE
        )
        
        if (length(hits) == 0L) return(NULL)
        
        data.frame(
          chr = chr,
          pos = start_i + BiocGenerics::start(hits) - 1L
        )
      })
    }
  }
  
  base_genome <- do.call(rbind, base_genome)
  
  if (is.null(base_genome) || nrow(base_genome) == 0L) {
    stop("No '", bases, "' motifs found.")
  }
  
  data.table::setDT(base_genome)
  base_genome <- unique(base_genome, by = c("chr", "pos"))
  
  base_genome[, chr_order := match(chr, chromosomes)]
  data.table::setorder(base_genome, chr_order, pos)
  base_genome[, chr_order := NULL]
  
  as.data.frame(base_genome)
}



# ---- Loading functions ----

load_genome <- function(genome_assembly,
                        sel_chr = NULL,
                        genome_fasta = NULL,
                        install_if_missing = FALSE) {
  
  if (!is.null(genome_fasta) &&
      !is.na(genome_fasta) &&
      trimws(genome_fasta) != "" &&
      !trimws(genome_fasta) %in% c("NULL", "null", "NA", "None", "none")) {
    
    genome_fasta <- normalizePath(genome_fasta, mustWork = TRUE)
    message("Loading reference genome from FASTA: ", genome_fasta)
    
    if (!requireNamespace("Biostrings", quietly = TRUE)) {
      stop("Package 'Biostrings' is required to load genome_fasta.", call. = FALSE)
    }
    
    genome <- Biostrings::readDNAStringSet(genome_fasta)
    
    chromosomes <- names(genome)
    
    if (!is.null(sel_chr)) {
      missing_chr <- sel_chr[!sel_chr %in% chromosomes]
      if (length(missing_chr) > 0L) {
        stop(
          "These chromosomes are not present in the FASTA genome: ",
          paste(missing_chr, collapse = ", "),
          call. = FALSE
        )
      }
    }
    
    genome <- genome[names(genome) %in% sel_chr]
    
  } else {
    message("Loading reference genome: ", genome_assembly, "...")
    
    if (inherits(genome_assembly, "BSgenome")) {
      
      genome <- genome_assembly
      
    } else if (is.character(genome_assembly) && length(genome_assembly) == 1L) {
      
      if (!requireNamespace("BSgenome", quietly = TRUE)) {
        stop("Package 'BSgenome' is required but not installed.", call. = FALSE)
      }
      
      genome_pkg <- switch(
        genome_assembly,
        "hg19" = "BSgenome.Hsapiens.UCSC.hg19",
        "hg38" = "BSgenome.Hsapiens.UCSC.hg38",
        genome_assembly
      )
      
      if (!requireNamespace(genome_pkg, quietly = TRUE)) {
        if (install_if_missing) {
          message("Installing missing BSgenome package: ", genome_pkg)
          
          if (!requireNamespace("BiocManager", quietly = TRUE)) {
            utils::install.packages("BiocManager", repos = "https://cloud.r-project.org")
          }
          
          BiocManager::install(genome_pkg, ask = FALSE, update = FALSE)
        } else {
          stop(
            "Required BSgenome package is not installed: ", genome_pkg, "\n",
            "Install it in the container, for example:\n",
            "BiocManager::install('", genome_pkg, "')",
            call. = FALSE
          )
        }
      }
      
      genome <- BSgenome::getBSgenome(
        genome_assembly,
        masked = FALSE,
        load.only = FALSE
      )
      
    } else {
      stop(
        "genome_assembly must be either a BSgenome object or a single character string.",
        call. = FALSE
      )
    }
    chromosomes <- genome@seqinfo@seqnames
    
    if (!is.null(sel_chr)) {
      missing_chr <- sel_chr[!sel_chr %in% chromosomes]
      if (length(missing_chr) > 0L) {
        stop(
          "These chromosomes are not present in the genome: ",
          paste(missing_chr, collapse = ", "),
          call. = FALSE
        )
      }
      genome <- Biostrings::DNAStringSet(
        lapply(sel_chr, function(chr) genome[[chr]])
      )
      names(genome) <- sel_chr    
    }
    
    
  }
  
  return(genome)
}


#' Load read coordinates from BED format
#'
#' @description
#' Efficiently loads per-read genomic coordinates from a BED file
#' (typically produced by `bedtools bamtobed`).  
#' Ensures correct column types, filters by MAPQ and (optionally) by chromosome.
#'
#' @param read_coord_bedfile Path to a BED file with **6 columns**:
#'   chr, start, end, readID, MAPQ/score, strand.
#' @param read_coord_1based
#' Logical value indicating whether the read alignment coordinates in
#' `read_coord_bedfile` are already reported using 1-based coordinates.
#' If `FALSE`, coordinates are assumed to follow the standard BED convention
#' with 0-based start positions and are internally converted when needed. (Default: FALSE)
#' @param mapq_th Minimum mapping quality required to retain a read.
#' @param sel_chr Optional character vector of chromosomes to keep.
#'   If `NULL`, all chromosomes are retained.
#' @param nThread Number of threads for `data.table::fread()`.
#' @param as_GRanges Logical value to return a GRanges object (default: FALSE).
#'
#' @return A `data.table` with columns:
#'   `chr`, `start`, `end`, `readID`, `score`, `strand`.
#'
#' @export
#'
#' @importFrom data.table fread setDT setnames
#'
#' @examples
#' \dontrun{
#' reads <- load_read_coords("reads.bed", mapq_th = 20)
#' }

load_read_coords <- function(read_coord_bedfile,
                             read_coord_1based = FALSE,
                             mapq_th,
                             sel_chr = NULL,
                             as_GRanges = FALSE,
                             nThread = data.table::getDTthreads()) {
  message("[INFO] Reading reads coordinates from: ", read_coord_bedfile)
  
  read_coords <- data.table::fread(
    read_coord_bedfile,
    header      = FALSE,
    colClasses  = list(
      character = c("V1", "V4", "V6"),  # chr, readID, strand
      integer   = c("V2", "V3"),        # start, end
      numeric   = "V5"                  # score / MAPQ
    ),
    nThread     = nThread,
    showProgress = TRUE
  )
  
  if (ncol(read_coords) != 6L) {
    stop("The provided read_coord_bedfile must have 6 columns!")
  }
  if (nrow(read_coords) == 0L) {
    stop("read_coord_bedfile has 0 rows - nothing to process.")
  }
  if (!is.numeric(read_coords[["V5"]])) {
    stop("Column 5 of read_coord_bedfile (score/MAPQ) must be numeric.")
  }
  
  data.table::setDT(read_coords)
  data.table::setnames(read_coords,
                       old = paste0("V", 1:6),
                       new = c("chr", "start", "end", "readID", "score", "strand"))
  
  if (!read_coord_1based) {
    read_coords[, start := start + 1L]
  }
  
  read_coords <- read_coords[score >= mapq_th]
  
  if (!is.null(sel_chr)) {
    read_coords <- read_coords[chr %in% sel_chr]
  }
  
  if (nrow(read_coords) == 0L) {
    stop("No reads left after filtering (MAPQ and/or chromosomes).")
  }
  
  # read_coords[, readID := sub("/[12]$", "", readID)]
  
  bad_reads <- read_coords[, .(n_chr = data.table::uniqueN(chr)), by = readID][n_chr > 1]
  
  if (nrow(bad_reads) > 0L) {
    warning("Some readIDs map to more than one chromosome. Keeping the first chromosome.")
  }
  
  # read_coords <- read_coords[
  #   ,
  #   .(
  #     chr    = chr[1],
  #     start  = min(start),
  #     end    = max(end),
  #     strand = "*"
  #   ),
  #   by = readID
  # ]
  
  if (as_GRanges){
    read_coords <- GenomicRanges::GRanges(
      seqnames = read_coords$chr,
      ranges   = IRanges::IRanges(start = read_coords$start,
                                  end   = read_coords$end)
    )
  }
  
  return(read_coords)
}


load_mod_calls <- function(modkit_file,
                           bismark_file,
                           mod_file_1based = FALSE,
                              base_qual_th,
                              sel_chr = NULL,
                              code_map,
                              nThread = data.table::getDTthreads()) {
  
  if (!is.null(modkit_file)){
    message("Reading modkit calls from: ", modkit_file)
    
    required_cols <- c(
      "read_id", "chrom", "ref_position",
      "call_code", "base_qual", "ref_strand"
    )
    
    mod_file <- data.table::fread(
      modkit_file,
      select      = required_cols,
      colClasses  = "character", 
      nThread     = nThread,
      showProgress = TRUE
    ) 
    
    missing_cols <- base::setdiff(required_cols, names(mod_file))
    if (length(missing_cols) > 0L) {
      stop("The modkit file is missing required columns: ",
           paste(missing_cols, collapse = ", "))
    }
  }
  
  if (!is.null(bismark_file)){
    message("Reading bismark calls from: ", bismark_file)
    
    required_cols <- c(
      "read_id", "chrom", "ref_position", "ref_strand", "call_code", "original_strand"
    )
    
    mod_file <- data.table::fread(
      bismark_file,
      nThread     = nThread,
      showProgress = TRUE
    ) 
    colnames(mod_file) <- required_cols
    
    mod_file <- mod_file %>% 
      dplyr::select(-ref_strand) %>% 
      dplyr::mutate(ref_strand = ifelse(original_strand == 'OB_CTOB', '-', 
                                        ifelse(original_strand == 'OT_CTOT', '+', '*'))) %>% 
      dplyr::select(-original_strand)
  }
  
  if (nrow(mod_file) == 0L) {
    stop("modkit_file has 0 rows - nothing to process.")
  }
  
  data.table::setDT(mod_file)
  
  mod_file[, bad_refpos := !grepl("^[0-9]+$", ref_position)]
  
  n_bad <- mod_file[bad_refpos == TRUE, .N]
  if (n_bad > 0L) {
    message("   [NOTE] Removing ", n_bad,
            " rows with non-numeric ref_position (likely header lines).")
    print(mod_file[bad_refpos == TRUE])
    mod_file <- mod_file[bad_refpos == FALSE]
  }
  
  mod_file[, bad_refpos := NULL] 
  
  if ('base_qual' %in% colnames(mod_file)) {
    mod_file[, `:=`(
      base_qual    = as.integer(base_qual),
      ref_position = as.integer(ref_position)
    )]
  }
  
  if (any(is.na(mod_file$ref_position))) {
    stop("Unexpected NA in ref_position after cleaning.")
  }
  if (any(is.na(mod_file$base_qual))) {
    stop("Unexpected NA in base_qual after cleaning.")
  }
  
  if ('base_qual' %in% colnames(mod_file) & base_qual_th > 0L ) {
    mod_file <- mod_file[base_qual >= base_qual_th]
    
    if (nrow(mod_file) == 0L) {
      stop("No mod calls pass base_qual >= ", base_qual_th, ".")
    }
  }
  
  data.table::setnames(mod_file, "chrom", "chr")
  
  if (!mod_file_1based) {
    mod_file[, ref_position_0based := ref_position]
    
    mod_file[
      ,
      ref_position := data.table::fifelse(
        ref_strand == "-",
        ref_position_0based,
        ref_position_0based + 1
      )
    ]
  }
  
  # base_key = chr_pos
  mod_file[, base_key := paste(chr, ref_position, sep = "_")]
  
  if (!is.null(sel_chr)) {
    mod_file <- mod_file[chr %in% sel_chr]
    if (nrow(mod_file) == 0L) {
      stop("No modkit calls on selected chromosomes: ",
           paste(sel_chr, collapse = ", "))
    }
  }
  
  # mapping call_code -> value tramite code_map
  val <- code_map[mod_file[["call_code"]]]
  unmapped <- is.na(val)
  if (any(unmapped)) {
    val[unmapped] <- code_map[["default"]]
  }
  mod_file[, value := as.integer(val)]
  
  mod_file[
    ,
    value := data.table::fifelse(
      ref_strand == "-",
      value * -1,
      value
    )
  ]
  
  return(mod_file[, .(read_id, chr, ref_position, ref_strand, base_key, value)])
}


load_mut_calls <- function(mut_file,
                           base_qual_th = 0,
                           base_map_qual_th = 0,
                           sel_chr = NULL,
                           mut_code_map = c("C_T" = 5, "C_G" = 6, "C_A" = 7,
                                            "T_C" = 8, "T_A" = 9, "T_G" = 10,
                                            "A_G" = 11, "A_T" = 12, "A_C" = 13,
                                            "G_C" = 14, "G_A" = 15, "G_T" = 16,
                                            "N_G" = 17, "N_C" = 18, "N_A" = 19, "N_T" = 20),
                           nThread = data.table::getDTthreads()) {
  message("Reading per read mutation calls from: ", mut_file)
  
  required_cols <- c(
    "read_id", "chrom", "ref_pos",
    "ref_base", "read_base", "strand",
    "base_qual", "mapq"
  )
  
  mut_file <- data.table::fread(
    mut_file,
    colClasses  = "character", 
    nThread     = nThread,
    showProgress = TRUE
  )
  
  if (nrow(mut_file) == 0L) {
    stop("mut_file has 0 rows - nothing to process.")
  }
  
  missing_cols <- base::setdiff(required_cols, names(mut_file))
  if (length(missing_cols) > 0L) {
    stop("The mutation file is missing required columns: ",
         paste(missing_cols, collapse = ", "))
  }
  
  data.table::setDT(mut_file)
  
  mut_file[, `:=`(
    base_qual    = as.integer(base_qual),
    mapq    = as.integer(mapq),
    ref_pos = as.integer(ref_pos)
  )]
  
  if (any(is.na(mut_file$ref_pos))) {
    stop("Unexpected NA in ref_position after cleaning.")
  }
  if (any(is.na(mut_file$base_qual))) {
    stop("Unexpected NA in base_qual after cleaning.")
  }
  
  if (base_qual_th > 0L) {
    mut_file <- mut_file[base_qual >= base_qual_th]
  }
  if (nrow(mut_file) == 0L) {
    stop("No mutation calls pass base_qual >= ", base_qual_th, ".")
  }
  
  if (base_map_qual_th > 0L) {
    mut_file <- mut_file[mapq >= base_map_qual_th]
  }
  if (nrow(mut_file) == 0L) {
    stop("No mutation calls pass mapq >= ", base_map_qual_th, ".")
  }
  
  data.table::setnames(mut_file, "chrom", "chr")
  
  mut_file[, ref_position_0based := ref_pos]
  
  mut_file[
    ,
    ref_pos := data.table::fifelse(
      strand == "-",
      ref_position_0based,
      ref_position_0based + 1
    )
  ]
  
  # base_key = chr_pos
  mut_file[, base_key := paste(chr, ref_pos, sep = "_")]
  
  # mutation_event 
  mut_file[, mut_event := paste(toupper(ref_base), toupper(read_base), sep = "_")]
  
  if (!is.null(sel_chr)) {
    mut_file <- mut_file[chr %in% sel_chr]
    if (nrow(mut_file) == 0L) {
      stop("No mutation calls on selected chromosomes: ",
           paste(sel_chr, collapse = ", "))
    }
  }
  
  # mapping call_code -> value tramite mut_code_map
  val <- mut_code_map[mut_file[["mut_event"]]]
  unmapped <- is.na(val)
  if (any(unmapped)) {
    mut_file <- mut_file[!unmapped]
  }
  mut_file[, value := as.integer(mut_code_map[mut_file[["mut_event"]]])]
  
  return(mut_file[, .(read_id, chr, ref_pos, base_key, value)])
}



# ---- modDfToSparseMat ----
build_sparse_matrix <- function(base_coords_df, read_coords_df, mod_df) {
  
  message("[STEP] Building paired-end sparse matrix...")
  
  #### 1. Reference target base index ####
  base_key <- paste(base_coords_df$chr, base_coords_df$pos, sep = "_")
  base_index <- stats::setNames(seq_along(base_key), base_key)
  
  #### 2. Normalize read IDs ####
  read_coords_df <- read_coords_df %>%
    dplyr::mutate(
      read_core = sub("(/1|/2)$", "", readID)
    )
  
  #### 3. Define fragment-level rows ordered by mapping start ####
  fragment_df <- read_coords_df %>%
    dplyr::group_by(read_core) %>%
    dplyr::summarise(
      chr = dplyr::first(chr),
      n_chr = dplyr::n_distinct(chr),
      fragment_start = min(start),
      fragment_end   = max(end),
      .groups = "drop"
    )
  
  if (any(fragment_df$n_chr > 1)) {
    warning(
      "Some read pairs map to more than one chromosome. ",
      "Number of affected fragments: ",
      sum(fragment_df$n_chr > 1)
    )
  }
  
  
  chr_levels <- c(paste0("chr", 1:22), "chrX", "chrY")
  
  fragment_df <- fragment_df %>%
    dplyr::mutate(chr = factor(chr, levels = chr_levels)) %>%
    dplyr::arrange(chr, fragment_start, fragment_end, read_core) %>%
    dplyr::mutate(chr = as.character(chr))
  
  fragment_ids <- fragment_df$read_core
  fragment_index <- stats::setNames(seq_along(fragment_ids), fragment_ids)
  
  #### 4. GRanges for read intervals ####
  read_gr <- GenomicRanges::GRanges(
    seqnames = read_coords_df$chr,
    ranges = IRanges::IRanges(
      start = read_coords_df$start,
      end   = read_coords_df$end
    )
  )
  
  #### 5. GRanges for target base positions ####
  base_gr <- GenomicRanges::GRanges(
    seqnames = base_coords_df$chr,
    ranges = IRanges::IRanges(
      start = base_coords_df$pos,
      end   = base_coords_df$pos
    )
  )
  
  #### 6. Overlap mate intervals with target bases ####
  hits <- GenomicRanges::findOverlaps(read_gr, base_gr)
  
  mate_rows <- S4Vectors::queryHits(hits)
  base_cols <- S4Vectors::subjectHits(hits)
  
  fragment_rows <- fragment_index[read_coords_df$read_core[mate_rows]]
  
  valid <- !is.na(fragment_rows)
  
  coverage_pairs <- unique(
    data.frame(
      row = as.integer(fragment_rows[valid]),
      col = as.integer(base_cols[valid])
    )
  )
  
  #### 7. Build sparse coverage matrix ####
  mat_base <- Matrix::sparseMatrix(
    i = coverage_pairs$row,
    j = coverage_pairs$col,
    x = 1L,
    dims = c(length(fragment_ids), nrow(base_coords_df)),
    dimnames = list(fragment_ids, base_key)
  )
  
  #### 8. Insert modification calls ####
  mod_df$col <- base_index[mod_df$base_key]
  
  cat(
    "[INFO] Number of mod calls not present in reference sites: ",
    sum(is.na(mod_df$col)),
    "\n"
  )
  
  f_mod_df <- mod_df[!is.na(mod_df$col), ]
  
  f_mod_df$read_core <- sub("(/1|/2)$", "", f_mod_df$read_id)
  f_mod_df$row <- fragment_index[f_mod_df$read_core]
  
  cat(
    "[INFO] Number of mod calls not matching any fragment row: ",
    sum(is.na(f_mod_df$row)),
    "\n"
  )
  
  f_mod_df <- f_mod_df[!is.na(f_mod_df$row), ]
  
  mat_base[cbind(f_mod_df$row, f_mod_df$col)] <- f_mod_df$value
  
  cat(
    "[INFO] Dimension of the generated sparse matrix: ",
    mat_base@Dim,
    "\n"
  )
  
  return(mat_base)
}


build_sparse_matrix_parallel_chunks <- function(
    base_coords_df,
    read_coords_df,
    mod_df,
    cores = 4,
    chunks_per_core = 10
) {
  
  message("[STEP] Building sparse matrix by genomic chunks using foreach...")
  
  data.table::setDT(mod_df)
  mod_df[, read_core := sub("/[12]$", "", read_id)]
  
  data.table::setDT(read_coords_df)
  read_coords_df[, read_core := sub("/[12]$", "", readID)]
  
  fragment_df <- read_coords_df[,
                                .(
                                  chr = chr[1L],
                                  n_chr = data.table::uniqueN(chr),
                                  fragment_start = min(start),
                                  fragment_end = max(end)
                                ),
                                by = read_core
  ]
  
  if (any(fragment_df$n_chr > 1)) {
    warning("Some read pairs map to more than one chromosome.")
  }
  
  chr_levels <- c(paste0("chr", 1:22), "chrX", "chrY", "chrM", "MT")
  
  fragment_df[, chr_order := match(chr, chr_levels)]
  data.table::setorder(
    fragment_df,
    chr_order,
    fragment_start,
    fragment_end,
    read_core
  )
  fragment_df[, chr_order := NULL]
  
  fragment_ids <- fragment_df$read_core
  fragment_index <- stats::setNames(seq_along(fragment_ids), fragment_ids)
  

  data.table::setDT(base_coords_df)
  base_coords_df[, base_key := paste(chr, pos, sep = "_")]
  base_coords_df[, chr_order := match(chr, chr_levels)]
  
  data.table::setorder(
    base_coords_df,
    chr_order,
    pos
  )
  
  base_coords_df[, chr_order := NULL]
  base_key <- base_coords_df$base_key
  
  
  n_chunks <- max(1L, cores * chunks_per_core)
  
  chunk_list <- prepare_sparse_chunks(
    base_coords_df = base_coords_df,
    read_coords_df = read_coords_df,
    mod_df = mod_df,
    n_chunks = n_chunks
  )
  
  message("[INFO] Number of chunks: ", length(chunk_list))
  
  if (cores > 1L) {
    
    cl <- parallel::makeCluster(cores, type = "PSOCK")
    doParallel::registerDoParallel(cl)
    
    on.exit({
      try(parallel::stopCluster(cl), silent = TRUE)
      foreach::registerDoSEQ()
    }, add = TRUE)
    
    mat_list <- tryCatch(
      {
        foreach::foreach(
          chunk = chunk_list,
          .packages = c("Matrix", "GenomicRanges", "IRanges", "S4Vectors"),
          .export = c("build_sparse_matrix_one_chunk")
        ) %dopar% {
          build_sparse_matrix_one_chunk(
            chunk = chunk,
            fragment_ids = fragment_ids,
            fragment_index = fragment_index
          )
        }
      },
      finally = {
        parallel::stopCluster(cl)
        foreach::registerDoSEQ()
      }
    )
    
  } else {
    
    mat_list <- lapply(
      chunk_list,
      build_sparse_matrix_one_chunk,
      fragment_ids = fragment_ids,
      fragment_index = fragment_index
    )
  }
  
  message("Combining sparse chunks...")
  mat_list <- mat_list[!vapply(mat_list, is.null, logical(1))]
  mat_base <- Reduce(Matrix::cbind2, mat_list)
  mat_base <- mat_base[, base_key, drop = FALSE]
  
  cat(
    "[INFO] Dimension of the generated sparse matrix: ",
    mat_base@Dim,
    "\n"
  )
  
  return(mat_base)
}


prepare_sparse_chunks <- function(
    base_coords_df,
    read_coords_df,
    mod_df,
    n_chunks
) {
  
  base_coords_df <- base_coords_df %>%
    dplyr::arrange(chr, pos)
  
  base_by_chr <- split(base_coords_df, base_coords_df$chr)
  
  chunk_list <- list()
  k <- 1L
  
  for (chr_i in names(base_by_chr)) {
    
    base_chr <- base_by_chr[[chr_i]]
    
    n_chr_chunks <- max(
      1L,
      round(nrow(base_chr) / nrow(base_coords_df) * n_chunks)
    )
    
    chr_split <- split(
      base_chr,
      cut(
        seq_len(nrow(base_chr)),
        breaks = n_chr_chunks,
        labels = FALSE
      )
    )
    
    for (block_base in chr_split) {
      
      block_start <- min(block_base$pos)
      block_end <- max(block_base$pos)
      
      block_reads <- read_coords_df[
        read_coords_df$chr == chr_i &
          read_coords_df$end >= block_start &
          read_coords_df$start <= block_end,
        ,
        drop = FALSE
      ]
      
      block_mod <- mod_df[
        mod_df$chr == chr_i &
          mod_df$ref_position >= block_start &
          mod_df$ref_position <= block_end,
        ,
        drop = FALSE
      ]
      
      chunk_list[[k]] <- list(
        chunk_id = k,
        chr = chr_i,
        start = block_start,
        end = block_end,
        block_base = block_base,
        block_reads = block_reads,
        block_mod = block_mod
      )
      
      k <- k + 1L
    }
  }
  
  chunk_list
}


build_sparse_matrix_one_chunk <- function(
    chunk,
    fragment_ids,
    fragment_index
) {
  
  block_base <- chunk$block_base
  block_reads <- chunk$block_reads
  block_mod <- chunk$block_mod
  
  empty_mat <- function() {
    Matrix::sparseMatrix(
      i = integer(0),
      j = integer(0),
      x = numeric(0),
      dims = c(length(fragment_ids), nrow(block_base)),
      dimnames = list(fragment_ids, block_base$base_key)
    )
  }
  
  if (nrow(block_base) == 0L) {
    return(empty_mat())
  }
  
  if (nrow(block_reads) == 0L) {
    
    mat <- empty_mat()
    
  } else {
    
    read_gr <- GenomicRanges::GRanges(
      seqnames = block_reads$chr,
      ranges = IRanges::IRanges(
        start = block_reads$start,
        end = block_reads$end
      )
    )
    
    base_gr <- GenomicRanges::GRanges(
      seqnames = block_base$chr,
      ranges = IRanges::IRanges(
        start = block_base$pos,
        end = block_base$pos
      )
    )
    
    hits <- GenomicRanges::findOverlaps(read_gr, base_gr)
    
    if (length(hits) == 0L) {
      
      mat <- empty_mat()
      
    } else {
      
      mate_rows <- S4Vectors::queryHits(hits)
      base_cols <- S4Vectors::subjectHits(hits)
      
      fragment_rows <- fragment_index[block_reads$read_core[mate_rows]]
      valid <- !is.na(fragment_rows)
      
      coverage_pairs <- unique(data.frame(
        row = as.integer(fragment_rows[valid]),
        col = as.integer(base_cols[valid])
      ))
      
      mat <- Matrix::sparseMatrix(
        i = coverage_pairs$row,
        j = coverage_pairs$col,
        x = 1L,
        dims = c(length(fragment_ids), nrow(block_base)),
        dimnames = list(fragment_ids, block_base$base_key)
      )
    }
  }
  
  if (nrow(block_mod) > 0L) {
    
    block_base_index <- stats::setNames(
      seq_len(nrow(block_base)),
      block_base$base_key
    )
    
    block_mod$col <- block_base_index[block_mod$base_key]
    block_mod$row <- fragment_index[block_mod$read_core]
    
    block_mod <- block_mod[
      !is.na(block_mod$row) & !is.na(block_mod$col),
      ,
      drop = FALSE
    ]
    
    if (nrow(block_mod) > 0L) {
      mat[cbind(block_mod$row, block_mod$col)] <- block_mod$value
    }
  }
  
  mat
}


filter_matrix <- function(mat_base, rm_zero_col = FALSE) {
  message('[STEP] Filtering sparse matrix...')
  zero_rows <- rownames(mat_base)[Matrix::rowSums(mat_base) == 0]
  f_mat_base <- mat_base[!(rownames(mat_base) %in% zero_rows), , drop = FALSE]
  
  if (rm_zero_col) {
    zero_cols <- colnames(f_mat_base)[Matrix::colSums(f_mat_base) == 0]
    if (length(zero_cols) > 0L) {
      f_mat_base <- f_mat_base[, !(colnames(f_mat_base) %in% zero_cols), drop = FALSE]
    }
  }
  
  cat(
    "[INFO] Dimension of the filtered sparse matrix: ",
    mat_base@Dim,
    "\n"
  )
  
  return(f_mat_base)
}



# ---- modDfToMhap ----
modDfToMhap <- function(
    mod_df,
    cpg_df,
    code_map_epiallele = c(`1` = 2, `2` = 0, `3` = 1, `4` = 0),
    read_col = "read_id",
    chr_col = "chr",
    pos_col = "ref_position",
    value_col = "value",
    strand_col = 'ref_strand',
    handle_missing_cpg = c("drop", "unknown", "split"),
    missing_code = "2",
    remove_ambiguous = FALSE,
    unknown_code = c(2),
    min_cpg_per_read = 1L,
    add_map_id = TRUE,
    return_read_map = TRUE,
    output_mhap_file = NULL,
    output_read_map_file = NULL,
    parallel = TRUE,
    n_workers = 4,
    chunks_per_core = 10
) {
  
  message("[STEP] Generating mHap object...")
  
  handle_missing_cpg <- match.arg(handle_missing_cpg)
  
  data.table::setDT(mod_df)
  data.table::setDT(cpg_df)
  
  required_cols <- c(read_col, chr_col, pos_col, value_col)
  missing_cols <- base::setdiff(required_cols, colnames(mod_df))
  
  if (length(missing_cols) > 0L) {
    stop(
      "Missing columns in `mod_df`: ",
      paste(missing_cols, collapse = ", ")
    )
  }
  
  cat("    [INFO] Normalizing CpG coordinates...\n")
  
  cpg_df <- normalize_cpg_df(cpg_df)
  
  if (nrow(cpg_df) == 0L) {
    stop("`cpg_df` has 0 valid CpG coordinates.")
  }
  
  data.table::setorder(cpg_df, chr, pos)
  cpg_df <- unique(cpg_df)
  
  cpg_df[
    ,
    cpg_rank := seq_len(.N),
    by = chr
  ]
  
  cpg_by_chr <- split(cpg_df, cpg_df$chr)
  
  cat("    [INFO] Preparing modification table...\n")
  dt <- data.table::data.table(
    read_id = as.character(mod_df[[read_col]]),
    chr = as.character(mod_df[[chr_col]]),
    pos = as.integer(mod_df[[pos_col]]),
    value = as.character(abs(mod_df[[value_col]]))
  )
  
  if (!is.null(strand_col) && strand_col %in% colnames(mod_df)) {
    dt[, strand := as.character(mod_df[[strand_col]])]
  } else {
    dt[, strand := "*"]
  }
  
  dt <- dt[
    !is.na(read_id) &
      !is.na(chr) &
      !is.na(pos) &
      !is.na(value)
  ]
  
  if (nrow(dt) == 0L) {
    stop("No valid rows in `mod_df`.")
  }
  
  cat("    [INFO] Matching modification calls to CpG coordinates...\n")
  
  dt <- merge(
    dt,
    cpg_df[, .(chr, pos, cpg_rank)],
    by = c("chr", "pos"),
    all = FALSE
  )
  
  if (nrow(dt) == 0L) {
    stop("No rows in `mod_df` overlap `cpg_df` coordinates.")
  }
  
  dt[, epi_code := base::unname(code_map_epiallele[value])]
  dt <- dt[!is.na(epi_code)]
  
  if (nrow(dt) == 0L) {
    stop("No rows remain after applying `code_map_epiallele`.")
  }
  
  dt[, epi_code := as.character(epi_code)]
  dt[!strand %in% c("+", "-", "*"), strand := "*"]
  
  data.table::setorder(dt, read_id, chr, cpg_rank)
  
  dt <- unique(
    dt,
    by = c("read_id", "chr", "pos")
  )
  
  if (nrow(dt) == 0L) {
    stop("No calls remain after removing duplicate read/CpG entries.")
  }
  
  cat("    [INFO] Preparing read-level chunks...\n")
  n_chunks <- if (isTRUE(parallel)) {
    max(1L, as.integer(n_workers) * as.integer(chunks_per_core))
  } else {
    1L
  }
  
  chunk_list <- make_mod_dt_read_chunks(
    dt = dt,
    n_chunks = n_chunks
  )
  
  cat("[INFO] Number of chunks: ", length(chunk_list), '\n')
  message("[STEP] Building read-level haplotypes...")
  
  if (isTRUE(parallel) && n_workers > 1L && length(chunk_list) > 1L) {
    
    cl <- parallel::makeCluster(n_workers, type = "PSOCK")
    doParallel::registerDoParallel(cl)
    
    read_hap_list <- tryCatch(
      {
        foreach::foreach(
          dt_chunk = chunk_list,
          .packages = c("data.table"),
          .export = c(
            "process_mod_dt_mhap_chunk",
            "build_read_hap_from_one_read"
          )
        ) %dopar% {
          process_mod_dt_mhap_chunk(
            dt_chunk = dt_chunk,
            cpg_by_chr = cpg_by_chr,
            handle_missing_cpg = handle_missing_cpg,
            missing_code = missing_code,
            unknown_code = unknown_code
          )
        }
      },
      finally = {
        try(parallel::stopCluster(cl), silent = TRUE)
        foreach::registerDoSEQ()
      }
    )
    
  } else {
    
    read_hap_list <- lapply(
      chunk_list,
      process_mod_dt_mhap_chunk,
      cpg_by_chr = cpg_by_chr,
      handle_missing_cpg = handle_missing_cpg,
      missing_code = missing_code,
      unknown_code = unknown_code
    )
  }
  
  read_hap_list <- read_hap_list[
    !vapply(read_hap_list, is.null, logical(1))
  ]
  
  read_hap_list <- read_hap_list[
    vapply(read_hap_list, nrow, integer(1)) > 0L
  ]
  
  if (length(read_hap_list) == 0L) {
    stop("No read-level haplotypes could be generated.")
  }
  
  message("[STEP] Combining read-level haplotypes...")
  
  read_hap <- data.table::rbindlist(
    read_hap_list,
    use.names = TRUE,
    fill = TRUE
  )
  
  read_hap <- read_hap[
    n_cpg >= min_cpg_per_read
  ]
  
  if (remove_ambiguous) {
    read_hap <- read_hap[
      is.na(has_unknown) | has_unknown == FALSE
    ]
  }
  
  if (nrow(read_hap) == 0L) {
    stop("No read-level haplotypes remain after filtering.")
  }
  
  message("[STEP] Aggregating read-level haplotypes into mHap records...")
  
  mhap_df <- read_hap[
    ,
    .(
      nreads = .N
    ),
    by = .(chr, start, end, epi, strand)
  ]
  
  data.table::setorder(mhap_df, chr, start, end, epi, strand)
  
  if (add_map_id) {
    mhap_df[, map_id := seq_len(.N)]
  }
  
  read_map_df <- NULL
  
  if (add_map_id && (return_read_map || !is.null(output_read_map_file))) {
    
    message("Generating map_id/read_id table...")
    
    read_map_df <- merge(
      read_hap[
        ,
        .(
          read_id,
          chr,
          start,
          end,
          epi,
          strand
        )
      ],
      mhap_df[
        ,
        .(
          chr,
          start,
          end,
          epi,
          strand,
          map_id
        )
      ],
      by = c("chr", "start", "end", "epi", "strand"),
      all.x = TRUE
    )
    
    read_map_df <- read_map_df[
      ,
      .(
        map_id = as.integer(map_id),
        read_id = as.character(read_id)
      )
    ]
    
    read_map_df <- unique(read_map_df)
    data.table::setorder(read_map_df, map_id, read_id)
  }
  
  if (add_map_id) {
    
    mhap_df <- mhap_df[
      ,
      .(
        chr = as.character(chr),
        start = as.integer(start),
        end = as.integer(end),
        epi = as.character(epi),
        nreads = as.integer(nreads),
        strand = as.character(strand),
        map_id = as.integer(map_id)
      )
    ]
    
  } else {
    
    mhap_df <- mhap_df[
      ,
      .(
        chr = as.character(chr),
        start = as.integer(start),
        end = as.integer(end),
        epi = as.character(epi),
        nreads = as.integer(nreads),
        strand = as.character(strand)
      )
    ]
  }
  
  if (!is.null(output_mhap_file)) {
    message("Writing mHap file to: ", output_mhap_file)
    
    data.table::fwrite(
      mhap_df,
      file = output_mhap_file,
      sep = "\t",
      col.names = FALSE,
      compress = "auto"
    )
  }
  
  if (!is.null(output_read_map_file) && !is.null(read_map_df)) {
    message("Writing mHap read map file to: ", output_read_map_file)
    
    data.table::fwrite(
      read_map_df,
      file = output_read_map_file,
      sep = "\t",
      col.names = TRUE,
      compress = "auto"
    )
  }
  
  message("mHap construction completed.")
  message("  [INFO] mHap records: ", nrow(mhap_df))
  message("  [INFO] read-level haplotypes: ", nrow(read_hap))
  
  list(
    mhap = mhap_df,
    read_map = read_map_df
  )
}

make_mod_dt_read_chunks <- function(
    dt,
    n_chunks = 1L
) {
  
  data.table::setDT(dt)
  
  if (nrow(dt) == 0L) {
    return(list(dt))
  }
  
  n_chunks <- max(1L, as.integer(n_chunks))
  
  read_load <- dt[
    ,
    .(
      n_calls = .N
    ),
    by = read_id
  ]
  
  n_chunks <- min(n_chunks, nrow(read_load))
  
  if (n_chunks <= 1L) {
    return(list(dt))
  }
  
  data.table::setorder(read_load, -n_calls)
  
  chunk_loads <- numeric(n_chunks)
  chunk_id <- integer(nrow(read_load))
  
  for (i in seq_len(nrow(read_load))) {
    j <- which.min(chunk_loads)
    chunk_id[i] <- j
    chunk_loads[j] <- chunk_loads[j] + read_load$n_calls[i]
  }
  
  read_load[, chunk := chunk_id]
  
  message("Chunk loads for mHap construction:")
  
  chunk_summary <- read_load[
    ,
    .(
      calls = sum(n_calls),
      reads = .N
    ),
    by = chunk
  ]
  
  data.table::setorder(chunk_summary, chunk)
  
  for (i in seq_len(nrow(chunk_summary))) {
    message(
      "  chunk ",
      chunk_summary$chunk[i],
      ": ",
      chunk_summary$calls[i],
      " calls and ",
      chunk_summary$reads[i],
      " reads"
    )
  }
  
  dt_chunked <- merge(
    dt,
    read_load[, .(read_id, chunk)],
    by = "read_id",
    all.x = TRUE
  )
  
  if (any(is.na(dt_chunked$chunk))) {
    stop("Some reads were not assigned to any chunk.")
  }
  
  chunk_vec <- dt_chunked$chunk
  
  dt_chunked[, chunk := NULL]
  
  chunk_list <- split(
    dt_chunked,
    chunk_vec
  )
  
  chunk_list <- chunk_list[
    vapply(chunk_list, nrow, integer(1)) > 0L
  ]
  
  chunk_list
}


process_mod_dt_mhap_chunk <- function(
    dt_chunk,
    cpg_by_chr,
    handle_missing_cpg = c("drop", "unknown", "split"),
    missing_code = "2",
    unknown_code = c(2)
) {
  
  handle_missing_cpg <- match.arg(handle_missing_cpg)
  
  data.table::setDT(dt_chunk)
  
  if (nrow(dt_chunk) == 0L) {
    return(data.table::data.table())
  }
  
  out <- dt_chunk[
    ,
    {
      cpg_ref_chr <- cpg_by_chr[[.BY$chr]]
      
      if (is.null(cpg_ref_chr) || nrow(cpg_ref_chr) == 0L) {
        data.table::data.table()
      } else {
        build_read_hap_from_one_read(
          pos = pos,
          cpg_rank = cpg_rank,
          epi_code = epi_code,
          strand = strand,
          chr = .BY$chr,
          cpg_ref_chr = cpg_ref_chr,
          handle_missing_cpg = handle_missing_cpg,
          missing_code = missing_code,
          unknown_code = unknown_code
        )
      }
    },
    by = .(read_id, chr)
  ]
  
  out
}


build_read_hap_from_one_read <- function(
    pos,
    cpg_rank,
    epi_code,
    strand,
    chr,
    cpg_ref_chr,
    handle_missing_cpg = c("drop", "unknown", "split"),
    missing_code = "2",
    unknown_code = c(2)
) {
  
  handle_missing_cpg <- match.arg(handle_missing_cpg)
  
  ord <- order(cpg_rank)
  
  pos <- pos[ord]
  cpg_rank <- cpg_rank[ord]
  epi_code <- epi_code[ord]
  
  strand <- strand[!is.na(strand)]
  strand <- unique(strand)
  
  strand_out <- if (length(strand) == 1L && strand %in% c("+", "-")) {
    strand
  } else {
    "*"
  }
  
  if (length(pos) == 0L) {
    return(data.table::data.table())
  }
  
  if (handle_missing_cpg == "split") {
    
    breaks <- c(1L, which(diff(cpg_rank) != 1L) + 1L)
    ends <- c(breaks[-1L] - 1L, length(cpg_rank))
    
    out <- vector("list", length(breaks))
    
    for (i in seq_along(breaks)) {
      
      idx <- breaks[i]:ends[i]
      
      if (length(idx) == 0L) {
        next
      }
      
      local_codes <- epi_code[idx]
      local_pos <- pos[idx]
      
      out[[i]] <- data.table::data.table(
        start = min(local_pos),
        end = max(local_pos),
        epi = paste0(local_codes, collapse = ""),
        n_cpg = length(local_codes),
        has_unknown = any(as.integer(local_codes) %in% unknown_code),
        strand = strand_out
      )
    }
    
    out <- out[!vapply(out, is.null, logical(1))]
    
    if (length(out) == 0L) {
      return(data.table::data.table())
    }
    
    return(
      data.table::rbindlist(
        out,
        use.names = TRUE,
        fill = TRUE
      )
    )
  }
  
  min_rank <- min(cpg_rank)
  max_rank <- max(cpg_rank)
  
  ref_span <- cpg_ref_chr[
    cpg_rank >= min_rank &
      cpg_rank <= max_rank
  ]
  
  if (nrow(ref_span) == 0L) {
    return(data.table::data.table())
  }
  
  expected_ranks <- ref_span$cpg_rank
  expected_pos <- ref_span$pos
  
  idx <- match(expected_ranks, cpg_rank)
  
  if (handle_missing_cpg == "drop") {
    
    if (any(is.na(idx))) {
      return(data.table::data.table())
    }
    
    local_codes <- epi_code[idx]
    
  } else if (handle_missing_cpg == "unknown") {
    
    local_codes <- rep(missing_code, length(expected_ranks))
    local_codes[!is.na(idx)] <- epi_code[idx[!is.na(idx)]]
    
  } else {
    
    stop("Unsupported `handle_missing_cpg`: ", handle_missing_cpg)
  }
  
  data.table::data.table(
    start = min(expected_pos),
    end = max(expected_pos),
    epi = paste0(local_codes, collapse = ""),
    n_cpg = length(local_codes),
    has_unknown = any(as.integer(local_codes) %in% unknown_code),
    strand = strand_out
  )
}


# mut_file Path to a VCF file containing SNP coordinates for each read.  
# mut_file_1based Logical. Whether the mutation file already uses
# 1-based inclusive coordinates. If `FALSE`, regions are interpreted as
# BED-like 0-based half-open intervals and the start coordinate is converted by
# adding 1. Default is `FALSE`.
# mut_code_map Named numeric vector that maps the mutation events reported in the vcf file to integer codes used in the matrix.
