#' Find group-specific shared epialleles
#'
#' @description
#' Identify epialleles that are shared by all samples of a target group and
#' absent from all samples belonging to the other groups.
#'
#' @details
#' The input is expected to be the concatenated epiallele table generated by
#' \code{epistats}, with one row per epiallele, genomic region, sample and
#' strand. A typical input contains columns such as \code{epi}, \code{Freq},
#' \code{id}, \code{strand}, \code{L1}, and \code{type}, where \code{L1}
#' identifies the sample and \code{type} identifies the biological or clinical
#' group.
#'
#' Each pair \code{id + epi} is treated as an epiallele event. The function
#' searches for events that satisfy both conditions:
#' \enumerate{
#'   \item the event is present in all samples of the target group;
#'   \item the event is absent from all samples outside the target group.
#' }
#'
#' If \code{restrict_to_common_regions = TRUE}, the analysis is first restricted
#' to regions that are present in all samples. This is recommended when absence
#' of an epiallele should be interpreted only among regions that were actually
#' analyzable in every sample. Regions that were discarded for a sample and
#' therefore do not appear in the epiallele table will be excluded from the
#' search.
#'
#' Presence is defined using \code{Freq >= min_freq}. If multiple rows with the
#' same sample, group, region and epiallele are present, their frequencies are
#' summed before testing group specificity.
#'
#' Parallelization is performed over target groups using
#' \code{foreach}/\code{doParallel}. This is most useful when the number of
#' groups is larger than one and the input table is large.
#'
#' @param epi_df A \code{data.frame} or \code{data.table} containing concatenated
#'   epiallele results across samples.
#' @param sample_col Character string. Name of the column containing sample
#'   identifiers. Default is \code{"L1"}.
#' @param group_col Character string. Name of the column containing group labels,
#'   such as histology or condition. Default is \code{"type"}.
#' @param region_col Character string. Name of the column containing genomic
#'   region identifiers. Default is \code{"id"}.
#' @param epi_col Character string. Name of the column containing epiallele
#'   patterns. Default is \code{"epi"}.
#' @param freq_col Character string. Name of the column containing epiallele
#'   counts or frequencies. Default is \code{"Freq"}.
#' @param min_freq Numeric. Minimum frequency/count required to consider an
#'   epiallele present in a sample. Default is \code{1}.
#' @param restrict_to_common_regions Logical. If \code{TRUE}, only regions
#'   present in all samples are retained before searching for group-specific
#'   epialleles. Default is \code{TRUE}.
#' @param groups Optional character vector specifying the groups to test as
#'   target groups. If \code{NULL}, all groups found in \code{group_col} are
#'   tested.
#' @param parallel Logical. Whether to parallelize the search across target
#'   groups using \code{foreach}/\code{doParallel}. Default is \code{FALSE}.
#' @param cores Integer. Number of parallel workers to use when
#'   \code{parallel = TRUE}. Default is \code{1}.
#' @param dt_threads Integer. Number of \code{data.table} threads to use inside
#'   each worker. Default is \code{1}, which helps avoid CPU oversubscription
#'   when using multiple parallel workers.
#' @param verbose Logical. Whether to print progress messages. Default is
#'   \code{TRUE}.
#'
#' @return A \code{data.frame} with one row per group-specific shared epiallele.
#'   The returned columns are:
#'   \describe{
#'     \item{\code{target_group}}{Group for which the epiallele is specific.}
#'     \item{\code{id}}{Genomic region identifier.}
#'     \item{\code{epi}}{Epiallele pattern.}
#'     \item{\code{n_target_samples}}{Number of samples in the target group.}
#'     \item{\code{n_present_target}}{Number of target-group samples in which
#'       the epiallele is present.}
#'     \item{\code{n_other_samples}}{Number of samples outside the target group.}
#'     \item{\code{n_present_other}}{Number of non-target samples in which the
#'       epiallele is present. For returned rows this is always \code{0}.}
#'     \item{\code{present_target_samples}}{Semicolon-separated list of target
#'       samples containing the epiallele.}
#'     \item{\code{present_other_samples}}{Semicolon-separated list of non-target
#'       samples containing the epiallele. For returned rows this is empty.}
#'     \item{\code{target_total_freq}}{Total epiallele frequency/count across
#'       target samples.}
#'     \item{\code{target_mean_freq}}{Mean epiallele frequency/count across
#'       target samples where the epiallele is present.}
#'     \item{\code{target_min_freq}}{Minimum epiallele frequency/count among
#'       target samples where the epiallele is present.}
#'     \item{\code{target_max_freq}}{Maximum epiallele frequency/count among
#'       target samples where the epiallele is present.}
#'     \item{\code{other_total_freq}}{Total epiallele frequency/count across
#'       non-target samples. For returned rows this is always \code{0}.}
#'   }
#'
#' @importFrom data.table as.data.table uniqueN rbindlist setorder setcolorder setDTthreads
#' @importFrom foreach foreach
#' @importFrom doParallel registerDoParallel
#' @importFrom parallel makeCluster stopCluster
#'
#' @export
#'
#' @examples
#' \dontrun{
#'   specific_epi <- findGrpSpecificEpi(
#'     epi_df = all_epi,
#'     sample_col = "L1",
#'     group_col = "type",
#'     region_col = "id",
#'     epi_col = "epi",
#'     freq_col = "Freq",
#'     min_freq = 1L,
#'     restrict_to_common_regions = TRUE,
#'     parallel = TRUE,
#'     cores = 4
#'   )
#'
#'   head(specific_epi)
#' }


findGrpSpecificEpi <- function(
    epi_df,
    sample_col = "L1",
    group_col = "type",
    region_col = "id",
    epi_col = "epi",
    freq_col = "Freq",
    min_freq = 1L,
    restrict_to_common_regions = TRUE,
    groups = NULL,
    parallel = FALSE,
    cores = 1L,
    dt_threads = 1L,
    verbose = TRUE
) {
  
  requireNamespace("data.table")
  
  dt <- data.table::as.data.table(epi_df)
  
  required_cols <- c(sample_col, group_col, region_col, epi_col, freq_col)
  missing_cols <- base::setdiff(required_cols, colnames(dt))
  
  if (length(missing_cols) > 0L) {
    stop(
      "Missing columns in `epi_df`: ",
      paste(missing_cols, collapse = ", ")
    )
  }
  
  dt <- dt[
    ,
    .(
      sample = as.character(get(sample_col)),
      group = as.character(get(group_col)),
      id = as.character(get(region_col)),
      epi = as.character(get(epi_col)),
      Freq = as.numeric(get(freq_col))
    )
  ]
  
  dt <- dt[
    !is.na(sample) &
      !is.na(group) &
      !is.na(id) &
      !is.na(epi) &
      !is.na(Freq)
  ]
  
  if (nrow(dt) == 0L) {
    stop("No valid rows in `epi_df`.")
  }
  
  sample_meta <- unique(dt[, .(sample, group)])
  
  duplicated_samples <- sample_meta[
    ,
    .N,
    by = sample
  ][N > 1L]
  
  if (nrow(duplicated_samples) > 0L) {
    stop(
      "Some samples are assigned to multiple groups: ",
      paste(duplicated_samples$sample, collapse = ", ")
    )
  }
  
  n_samples_total <- data.table::uniqueN(sample_meta$sample)
  
  if (isTRUE(verbose)) {
    message("Total samples: ", n_samples_total)
    message("Groups: ", paste(sort(unique(sample_meta$group)), collapse = ", "))
  }
  
  # ------------------------------------------------------------
  # 1. Keep only regions present in all samples
  # ------------------------------------------------------------
  
  if (isTRUE(restrict_to_common_regions)) {
    
    region_presence <- unique(dt[, .(sample, id)])[
      ,
      .(
        n_samples_with_region = data.table::uniqueN(sample)
      ),
      by = id
    ]
    
    common_regions <- region_presence[
      n_samples_with_region == n_samples_total,
      id
    ]
    
    if (isTRUE(verbose)) {
      message(
        "Regions before common-region filtering: ",
        data.table::uniqueN(dt$id)
      )
      
      message(
        "Regions present in all samples: ",
        length(common_regions)
      )
    }
    
    dt <- dt[id %in% common_regions]
    
    if (nrow(dt) == 0L) {
      stop("No rows remain after filtering to common regions.")
    }
  }
  
  # ------------------------------------------------------------
  # 2. Define groups
  # ------------------------------------------------------------
  
  if (is.null(groups)) {
    groups <- sort(unique(sample_meta$group))
  } else {
    groups <- as.character(groups)
    missing_groups <- base::setdiff(groups, unique(sample_meta$group))
    
    if (length(missing_groups) > 0L) {
      stop(
        "The following groups are not present in `epi_df`: ",
        paste(missing_groups, collapse = ", ")
      )
    }
  }
  
  # ------------------------------------------------------------
  # 3. Presence table: sample-region-epiallele
  # ------------------------------------------------------------
  
  present_dt <- dt[
    Freq >= min_freq,
    .(
      Freq = sum(Freq, na.rm = TRUE)
    ),
    by = .(sample, group, id, epi)
  ]
  
  if (nrow(present_dt) == 0L) {
    stop("No epialleles pass `min_freq`.")
  }
  
  # ------------------------------------------------------------
  # 4. Search group-specific shared epialleles
  # ------------------------------------------------------------
  
  use_parallel <- isTRUE(parallel) &&
    as.integer(cores) > 1L &&
    length(groups) > 1L
  
  if (isTRUE(use_parallel)) {
    
    if (!requireNamespace("foreach", quietly = TRUE)) {
      stop("Package `foreach` is required for parallel execution.")
    }
    
    if (!requireNamespace("doParallel", quietly = TRUE)) {
      stop("Package `doParallel` is required for parallel execution.")
    }
    
    n_workers <- min(as.integer(cores), length(groups))
    
    if (isTRUE(verbose)) {
      message("Running group-specific search in parallel with ", n_workers, " workers.")
    }
    
    cl <- parallel::makeCluster(n_workers)
    
    on.exit({
      try(parallel::stopCluster(cl), silent = TRUE)
      try(foreach::registerDoSEQ(), silent = TRUE)
    }, add = TRUE)
    
    doParallel::registerDoParallel(cl)
    
    foreach_obj <- foreach::foreach(
      target_group = groups,
      .packages = c("data.table"),
      .export = c(
        "findGrpSpecificSharedEpiallelesOneGroup",
        "GrpSpecificSharedEpiallelesDT"
      )
    )
    
    out_list <- foreach::`%dopar%`(
      foreach_obj,
      {
        data.table::setDTthreads(dt_threads)
        
        findGrpSpecificSharedEpiallelesOneGroup(
          target_group = target_group,
          sample_meta = sample_meta,
          present_dt = present_dt
        )
      }
    )
    
  } else {
    
    if (isTRUE(verbose)) {
      message("Running group-specific search sequentially.")
    }
    
    old_threads <- data.table::getDTthreads()
    on.exit(data.table::setDTthreads(old_threads), add = TRUE)
    data.table::setDTthreads(dt_threads)
    
    out_list <- lapply(
      groups,
      findGrpSpecificSharedEpiallelesOneGroup,
      sample_meta = sample_meta,
      present_dt = present_dt
    )
  }
  
  out <- data.table::rbindlist(
    out_list,
    use.names = TRUE,
    fill = TRUE
  )
  
  if (nrow(out) == 0L) {
    if (isTRUE(verbose)) {
      message("No group-specific shared epialleles found.")
    }
    return(data.frame())
  }
  
  final_cols <- c(
    "target_group",
    "id",
    "epi",
    "n_target_samples",
    "n_present_target",
    "n_other_samples",
    "n_present_other",
    "present_target_samples",
    "present_other_samples",
    "target_total_freq",
    "target_mean_freq",
    "target_min_freq",
    "target_max_freq",
    "other_total_freq"
  )
  
  data.table::setcolorder(out, final_cols)
  
  data.table::setorder(
    out,
    target_group,
    id,
    epi
  )
  
  as.data.frame(out)
}



emptyGrpSpecificSharedEpiallelesDT <- function() {
  
  data.table::data.table(
    target_group = character(),
    id = character(),
    epi = character(),
    n_target_samples = integer(),
    n_present_target = integer(),
    n_other_samples = integer(),
    n_present_other = integer(),
    present_target_samples = character(),
    present_other_samples = character(),
    target_total_freq = numeric(),
    target_mean_freq = numeric(),
    target_min_freq = numeric(),
    target_max_freq = numeric(),
    other_total_freq = numeric()
  )
}


findGrpSpecificSharedEpiallelesOneGroup <- function(
    target_group,
    sample_meta,
    present_dt
) {
  
  target_samples <- sample_meta[
    group == target_group,
    sample
  ]
  
  other_samples <- sample_meta[
    group != target_group,
    sample
  ]
  
  n_target_samples <- length(target_samples)
  n_other_samples <- length(other_samples)
  
  if (n_target_samples == 0L) {
    return(emptyGrpSpecificSharedEpiallelesDT())
  }
  
  target_presence <- present_dt[
    group == target_group,
    .(
      n_present_target = data.table::uniqueN(sample),
      present_target_samples = paste(sort(unique(sample)), collapse = ";"),
      target_total_freq = sum(Freq, na.rm = TRUE),
      target_mean_freq = mean(Freq, na.rm = TRUE),
      target_min_freq = min(Freq, na.rm = TRUE),
      target_max_freq = max(Freq, na.rm = TRUE)
    ),
    by = .(id, epi)
  ]
  
  if (nrow(target_presence) == 0L) {
    return(emptyGrpSpecificSharedEpiallelesDT())
  }
  
  other_presence <- present_dt[
    group != target_group,
    .(
      n_present_other = data.table::uniqueN(sample),
      present_other_samples = paste(sort(unique(sample)), collapse = ";"),
      other_total_freq = sum(Freq, na.rm = TRUE)
    ),
    by = .(id, epi)
  ]
  
  candidate <- merge(
    target_presence,
    other_presence,
    by = c("id", "epi"),
    all.x = TRUE
  )
  
  candidate[
    is.na(n_present_other),
    `:=`(
      n_present_other = 0L,
      present_other_samples = "",
      other_total_freq = 0
    )
  ]
  
  candidate[
    ,
    `:=`(
      target_group = target_group,
      n_target_samples = n_target_samples,
      n_other_samples = n_other_samples
    )
  ]
  
  candidate <- candidate[
    n_present_target == n_target_samples &
      n_present_other == 0L
  ]
  
  if (nrow(candidate) == 0L) {
    return(emptyGrpSpecificSharedEpiallelesDT())
  }
  
  final_cols <- c(
    "target_group",
    "id",
    "epi",
    "n_target_samples",
    "n_present_target",
    "n_other_samples",
    "n_present_other",
    "present_target_samples",
    "present_other_samples",
    "target_total_freq",
    "target_mean_freq",
    "target_min_freq",
    "target_max_freq",
    "other_total_freq"
  )
  
  data.table::setcolorder(candidate, final_cols)
  
  candidate
}