#' Identify covered genomic regions directly from mHap records
#'
#' `getCoveredRegFromMhap()` identifies genomic regions containing CpG sites
#' covered above a user-defined read-count threshold, using mHap records directly
#' instead of a read-by-CpG sparse matrix.
#'
#' This function is the mHap-based counterpart of `getCoveredReg()`. Instead of
#' computing CpG coverage from `Matrix::colSums(sparseMat != 0)`, it calculates
#' the coverage of each CpG as the sum of the `nreads` values of all mHap records
#' overlapping that CpG.
#'
#' @param mhap_obj Optional list. A lightweight mHap object generated by
#' `loadInputFromMhap(output_type = "mhap")` or
#' `loadInputFromMhap(output_type = "both")`. It should contain at least:
#' \describe{
#'   \item{`mhap`}{A data table of mHap records.}
#'   \item{`cpg_df`}{A data table of CpG coordinates to use as target sites.}
#' }
#' If `mhap_obj` is provided, `mhap_df` and `cpg_df` are automatically extracted
#' from it unless explicitly supplied.
#'
#' @param mhap_df Optional `data.table` or `data.frame`. Table of mHap records
#' with at least the columns `chr`, `start`, `end`, and `nreads`.
#' Required if `mhap_obj` is not provided.
#'
#' @param cpg_df Optional `data.table` or `data.frame`. CpG coordinate table with
#' columns `chr` and `pos`, or any format accepted by `normalize_cpg_df()`.
#' Required if `mhap_obj` is not provided.
#'
#' @param threshold Integer. Minimum CpG coverage required for a CpG site to be
#' considered covered. Coverage is computed as the sum of `nreads` values from
#' all mHap records overlapping the CpG. Default is `10`.
#'
#' @param minsize Integer. Minimum genomic size required for a covered region to
#' be retained. Regions with `end - start < minsize` are discarded. Default is
#' `50`.
#'
#' @param cores Integer. Number of parallel workers used to process chromosomes.
#' If `cores = 1`, chromosomes are processed sequentially. Default is `1`.
#'
#' @return A `GenomicRanges::GRanges` object containing covered genomic regions.
#' Each region corresponds to a run of consecutive CpG sites whose mHap-derived
#' coverage is greater than or equal to `threshold`, after filtering by
#' `minsize`.
#'
#' @details
#' The function works directly on compressed mHap records. Since mHap records
#' aggregate identical methylation haplotypes through their `nreads` field, CpG
#' coverage is computed by summing `nreads` over all mHap intervals overlapping
#' each CpG position.
#'
#' This avoids materializing a potentially large read-by-CpG sparse matrix and
#' is therefore more suitable for mHap-native workflows such as
#' `makeWindowsFromMhap()` and `epiAnalysisFromMhap()`.
#'
#' If `mhap_obj$cpg_df` was previously restricted to a set of genomic regions,
#' only those CpGs are considered when computing covered regions.
#'
#' @examples
#' \dontrun{
#' inputMhap <- loadInputFromMhap(
#'   mhap_file = "sample.mhap.gz",
#'   cpg_file = "hg19_CpG.gz",
#'   sel_chr = "chr22",
#'   output_type = "mhap"
#' )
#'
#' coveredReg <- getCoveredRegFromMhap(
#'   mhap_obj = inputMhap$mhap_obj,
#'   threshold = 10,
#'   minsize = 50,
#'   cores = 4
#' )
#' }
#'
#' @import GenomicRanges
#' @import IRanges
#' @import S4Vectors
#' @import foreach
#' @import doParallel
#' @importFrom data.table setDT setorder rbindlist :=
#' @export


getCoveredRegFromMhap <- function(
    mhap_obj = NULL,
    mhap_df = NULL,
    cpg_df = NULL,
    threshold = 10,
    minsize = 50,
    cores = 1
) {
  
  if (!is.null(mhap_obj)) {
    
    if (is.null(mhap_df)) {
      mhap_df <- mhap_obj$mhap
    }
    
    if (is.null(cpg_df)) {
      cpg_df <- mhap_obj$cpg_df
    }
  }
  
  if (is.null(mhap_df)) {
    stop("mhap_df is NULL. Provide either mhap_obj or mhap_df.")
  }
  
  if (is.null(cpg_df)) {
    stop("cpg_df is NULL. Provide either mhap_obj$cpg_df or cpg_df.")
  }
  
  data.table::setDT(mhap_df)
  data.table::setDT(cpg_df)
  
  cpg_df <- normalize_cpg_df(cpg_df)
  
  mhap_df <- mhap_df[
    !is.na(chr) &
      !is.na(start) &
      !is.na(end) &
      start <= end &
      !is.na(nreads) &
      nreads > 0L
  ]
  
  if (nrow(mhap_df) == 0L) {
    stop("No valid mHap records available.")
  }
  
  if (nrow(cpg_df) == 0L) {
    stop("No CpG coordinates available.")
  }
  
  data.table::setorder(cpg_df, chr, pos)
  data.table::setorder(mhap_df, chr, start, end)
  
  chrs <- base::intersect(unique(cpg_df$chr), unique(mhap_df$chr))
  
  if (length(chrs) == 0L) {
    cat("No common chromosomes between mhap_df and cpg_df\n")
    return(
      GenomicRanges::GRanges(
        seqnames = character(),
        ranges = IRanges::IRanges(start = integer(), end = integer())
      )
    )
  }
  
  cat("Filtering positions with minimum coverage", threshold, "\n")
  cat("Computing CpG coverage directly from mHap records...\n")
  
  if (cores > 1L) {
    
    cl <- parallel::makeCluster(cores, type = "PSOCK")
    doParallel::registerDoParallel(cl)
    
    on.exit({
      try(parallel::stopCluster(cl), silent = TRUE)
      foreach::registerDoSEQ()
    }, add = TRUE)
    
    out_list <- tryCatch(
      {
        foreach::foreach(
          chr_name = chrs,
          .packages = c("data.table", "GenomicRanges", "IRanges", "S4Vectors"),
          .export = c("getCoveredRegFromMhap_one_chr")
        ) %dopar% {
          getCoveredRegFromMhap_one_chr(
            chr_name = chr_name,
            mhap_df = mhap_df,
            cpg_df = cpg_df,
            threshold = threshold
          )
        }
      },
      finally = {
        try(parallel::stopCluster(cl), silent = TRUE)
        foreach::registerDoSEQ()
      }
    )
    
  } else {
    
    out_list <- lapply(
      chrs,
      function(chr_name) {
        getCoveredRegFromMhap_one_chr(
          chr_name = chr_name,
          mhap_df = mhap_df,
          cpg_df = cpg_df,
          threshold = threshold
        )
      }
    )
  }
  
  out_list <- out_list[!vapply(out_list, is.null, logical(1))]
  
  if (length(out_list) == 0L) {
    cat("Any site has a coverage >=", threshold, "\n")
    return(
      GenomicRanges::GRanges(
        seqnames = character(),
        ranges = IRanges::IRanges(start = integer(), end = integer())
      )
    )
  }
  
  bed <- data.table::rbindlist(out_list, use.names = TRUE, fill = TRUE)
  
  if (nrow(bed) == 0L) {
    cat("Any site has a coverage >=", threshold, "\n")
    return(
      GenomicRanges::GRanges(
        seqnames = character(),
        ranges = IRanges::IRanges(start = integer(), end = integer())
      )
    )
  }
  
  data.table::setorder(bed, chr, start)
  
  cat("Number of covered regions:", nrow(bed), "\n")
  
  bed <- bed[end - start >= minsize]
  
  cat(
    "Number of covered regions after filtering for minsize =",
    minsize,
    ":",
    nrow(bed),
    "\n"
  )
  
  if (nrow(bed) == 0L) {
    return(
      GenomicRanges::GRanges(
        seqnames = character(),
        ranges = IRanges::IRanges(start = integer(), end = integer())
      )
    )
  }
  
  gr_bed <- GenomicRanges::makeGRangesFromDataFrame(
    as.data.frame(bed),
    keep.extra.columns = TRUE
  )
  
  cat("done\n")
  
  gr_bed
}


getCoveredRegFromMhap_one_chr <- function(
    chr_name,
    mhap_df,
    cpg_df,
    threshold = 10
) {
  
  cpg_chr <- cpg_df[chr == chr_name]
  mhap_chr <- mhap_df[chr == chr_name]
  
  if (nrow(cpg_chr) == 0L || nrow(mhap_chr) == 0L) {
    return(NULL)
  }
  
  data.table::setorder(cpg_chr, pos)
  
  chr_min <- min(cpg_chr$pos)
  chr_max <- max(cpg_chr$pos)
  
  mhap_chr <- mhap_chr[
    end >= chr_min &
      start <= chr_max
  ]
  
  if (nrow(mhap_chr) == 0L) {
    return(NULL)
  }
  
  mhap_gr <- GenomicRanges::GRanges(
    seqnames = mhap_chr$chr,
    ranges = IRanges::IRanges(
      start = mhap_chr$start,
      end = mhap_chr$end
    )
  )
  
  cpg_gr <- GenomicRanges::GRanges(
    seqnames = cpg_chr$chr,
    ranges = IRanges::IRanges(
      start = cpg_chr$pos,
      end = cpg_chr$pos
    )
  )
  
  hits <- GenomicRanges::findOverlaps(
    mhap_gr,
    cpg_gr,
    ignore.strand = TRUE
  )
  
  if (length(hits) == 0L) {
    return(NULL)
  }
  
  cov_dt <- data.table::data.table(
    cpg_idx = S4Vectors::subjectHits(hits),
    nreads = mhap_chr$nreads[S4Vectors::queryHits(hits)]
  )
  
  cov_dt <- cov_dt[
    ,
    .(coverage = sum(nreads, na.rm = TRUE)),
    by = cpg_idx
  ]
  
  cov_vec <- numeric(nrow(cpg_chr))
  cov_vec[cov_dt$cpg_idx] <- cov_dt$coverage
  
  covered_vec <- cov_vec >= threshold
  
  if (!any(covered_vec)) {
    return(NULL)
  }
  
  coords <- cpg_chr$pos
  
  r <- rle(covered_vec)
  run_end <- cumsum(r$lengths)
  run_start <- run_end - r$lengths + 1L
  
  true_runs <- which(r$values)
  
  if (length(true_runs) == 0L) {
    return(NULL)
  }
  
  true_start_indexes <- run_start[true_runs]
  true_end_indexes <- run_end[true_runs]
  
  data.table::data.table(
    chr = chr_name,
    start = coords[true_start_indexes],
    end = coords[true_end_indexes]
  )
}