#' Designing fixed-width windows from mHap CpG coordinates
#'
#' @description
#' This function builds flexible-width genomic windows directly from targte base positions
#' stored in an mHap input object, without requiring a read-by-CpG sparse matrix.
#'
#' The function is the mHap-native counterpart of `makeBinsFromSparse()`.
#' CpG positions are taken from `mhap_obj$cpg_df`, or alternatively from a
#' user-provided `cpg_df`. Candidate bins are created by
#' generating not-redundant genomic ranges that contain n target base positions.
#' All bins are then filtered according to the minimum and maximum bin size
#' (between \code{min.binsize} and \code{max.binsize}).
#'
#' If mHap records are provided, the number of reads overlapping each window is
#' computed as the sum of the `nreads` values of all mHap records overlapping
#' the window.
#'
#' @param mhap_obj Optional list generated by `loadInputFromMhap()`, usually
#' with `output_type = "mhap"` or `output_type = "both"`. The object should
#' contain at least `cpg_df`, and optionally `mhap`.
#'
#' @param cov_regs A `GenomicRanges::GRanges` object specifying the genomic
#' regions where windows are allowed. Only windows entirely contained within
#' these regions are kept. This can be generated by `getCoveredRegFromMhap()`.
#'
#' @param cpg_df Optional CpG coordinate table. Required only if `mhap_obj` is
#' not provided. The table must contain columns `chr` and `pos`, or any format
#' accepted by `normalize_cpg_df()`.
#'
#' @param mhap_df Optional mHap table. If provided, or if available as
#' `mhap_obj$mhap`, the number of reads overlapping each window is computed
#' by summing the `nreads` field of overlapping mHap records.
#' 
#' @param n An integer indicating the number of CpGs sites to be contained in the target region.
#' 
#' @param min.binsize An integer indicating the minimum length size of each bin
#' 
#' @param max.binsize An integer indicating the maximum length size of each bin
#' 
#' @param add_num_reads Logical. Whether to add a `num_reads` metadata column
#' by summing mHap `nreads` over records overlapping each window. Default is
#' `TRUE`.
#'
#' @return A `GenomicRanges::GRanges` object containing selected windows. Each
#' range has at least the metadata column `num_cpg`. If mHap records are
#' available and `add_num_reads = TRUE`, an additional metadata column
#' `num_reads` is added.
#'
#' @export


makeBinsFromMhap <- function(
    mhap_obj = NULL,
    cov_regs,
    cpg_df = NULL,
    mhap_df = NULL,
    n = 4,
    min.binsize  = 50L,
    max.binsize  = 150L,
    add_num_reads = TRUE
) {
  
  if (!methods::is(cov_regs, "GRanges")) {
    stop("`cov_regs` must be a GRanges object.")
  }
  
  if (!is.null(mhap_obj)) {
    
    if (is.null(cpg_df)) {
      cpg_df <- mhap_obj$cpg_df
    }
    
    if (is.null(mhap_df)) {
      mhap_df <- mhap_obj$mhap
    }
  }
  
  if (is.null(cpg_df)) {
    stop("`cpg_df` is NULL. Provide either `mhap_obj$cpg_df` or `cpg_df`.")
  }
  
  cpg_df <- normalize_cpg_df(cpg_df)
  data.table::setDT(cpg_df)
  
  if (nrow(cpg_df) == 0L) {
    message("No CpG coordinates available.")
    return(GenomicRanges::GRanges())
  }
  
  # Restrict CpGs to covered regions first.
  cpg_df <- filter_cpg_by_regions(
    cpg_df = cpg_df,
    regions_gr = cov_regs
  )
  
  if (nrow(cpg_df) == 0L) {
    message("No CpG coordinates fall within `cov_regs`.")
    return(GenomicRanges::GRanges())
  }
  
  data.table::setorder(cpg_df, chr, pos)
  
  bins_2cpg <- makeCpgCountBins(
    cpg_df = cpg_df,
    n = n,
    min.binsize  = min.binsize,
    max.binsize  = max.binsize
  )
  
  if (length(bins_2cpg) == 0L) {
    message("No bins generated from mHap CpG coordinates.")
    return(GenomicRanges::GRanges())
  }
  
  # Optional: compute mHap-derived read counts per window.
  if (isTRUE(add_num_reads) && !is.null(mhap_df)) {
    
    num_reads <- count_mhap_reads_over_windows(
      windows_gr = bins_2cpg,
      mhap_df = mhap_df
    )
    
    S4Vectors::mcols(bins_2cpg)$num_reads <- num_reads
  }
  
  return(bins_2cpg)
}

#' Count mHap reads overlapping genomic windows
#'
#' Internal helper used by `makeWindowsFromMhap()`. For each window, it sums
#' the `nreads` values of all mHap records overlapping that window.
#'
#' @param windows_gr A `GRanges` object containing genomic windows.
#' @param mhap_df A data table of mHap records with columns `chr`, `start`,
#' `end`, and `nreads`.
#'
#' @return Integer or numeric vector with one value per window.
#'
#' @keywords internal
#' @noRd

count_mhap_reads_over_windows <- function(
    windows_gr,
    mhap_df
) {
  
  data.table::setDT(mhap_df)
  
  mhap_df <- mhap_df[
    !is.na(chr) &
      !is.na(start) &
      !is.na(end) &
      start <= end &
      !is.na(nreads) &
      nreads > 0L
  ]
  
  if (nrow(mhap_df) == 0L || length(windows_gr) == 0L) {
    return(rep(0L, length(windows_gr)))
  }
  
  mhap_gr <- GenomicRanges::GRanges(
    seqnames = mhap_df$chr,
    ranges = IRanges::IRanges(
      start = mhap_df$start,
      end = mhap_df$end
    )
  )
  
  hits <- GenomicRanges::findOverlaps(
    windows_gr,
    mhap_gr,
    ignore.strand = TRUE
  )
  
  if (length(hits) == 0L) {
    return(rep(0L, length(windows_gr)))
  }
  
  read_dt <- data.table::data.table(
    win_idx = S4Vectors::queryHits(hits),
    nreads = mhap_df$nreads[S4Vectors::subjectHits(hits)]
  )
  
  read_dt <- read_dt[
    ,
    .(num_reads = sum(nreads, na.rm = TRUE)),
    by = win_idx
  ]
  
  out <- numeric(length(windows_gr))
  out[read_dt$win_idx] <- read_dt$num_reads
  
  out
}