#' Designing fixed-width windows from mHap CpG coordinates
#'
#' @description
#' This function builds fixed-width genomic windows directly from CpG positions
#' stored in an mHap input object, without requiring a read-by-CpG sparse matrix.
#'
#' The function is the mHap-native counterpart of `makeWindowsFromSparse()`.
#' CpG positions are taken from `mhap_obj$cpg_df`, or alternatively from a
#' user-provided `cpg_df`. For each CpG position, two candidate windows are
#' created:
#' \itemize{
#'   \item a left-anchored window: \code{[pos - window + 1, pos]}
#'   \item a right-anchored window: \code{[pos, pos + window - 1]}
#' }
#'
#' Candidate windows are filtered according to the number of CpGs they contain
#' and only windows fully contained within `cov_regs` are retained.
#'
#' If mHap records are provided, the number of reads overlapping each window is
#' computed as the sum of the `nreads` values of all mHap records overlapping
#' the window.
#'
#' @param mhap_obj Optional list generated by `loadInputFromMhap()`, usually
#' with `output_type = "mhap"` or `output_type = "both"`. The object should
#' contain at least `cpg_df`, and optionally `mhap`.
#'
#' @param cov_regs A `GenomicRanges::GRanges` object specifying the genomic
#' regions where windows are allowed. Only windows entirely contained within
#' these regions are kept. This can be generated by `getCoveredRegFromMhap()`.
#'
#' @param cpg_df Optional CpG coordinate table. Required only if `mhap_obj` is
#' not provided. The table must contain columns `chr` and `pos`, or any format
#' accepted by `normalize_cpg_df()`.
#'
#' @param mhap_df Optional mHap table. If provided, or if available as
#' `mhap_obj$mhap`, the number of reads overlapping each window is computed
#' by summing the `nreads` field of overlapping mHap records.
#'
#' @param window Integer scalar indicating the window size in base pairs.
#' Default is `50`.
#'
#' @param min.C Integer scalar indicating the minimum number of CpGs required
#' for a window to be retained. Default is `2`.
#'
#' @param max.C Integer scalar indicating the maximum number of CpGs allowed
#' in a window. Default is `50`.
#'
#' @param add_num_reads Logical. Whether to add a `num_reads` metadata column
#' by summing mHap `nreads` over records overlapping each window. Default is
#' `TRUE`.
#'
#' @return A `GenomicRanges::GRanges` object containing selected windows. Each
#' range has at least the metadata column `num_cpg`. If mHap records are
#' available and `add_num_reads = TRUE`, an additional metadata column
#' `num_reads` is added.
#'
#' @export
makeWindowsFromMhap <- function(
    mhap_obj = NULL,
    cov_regs,
    cpg_df = NULL,
    mhap_df = NULL,
    window = 50L,
    min.C = 2L,
    max.C = 50L,
    add_num_reads = TRUE
) {
  
  if (!methods::is(cov_regs, "GRanges")) {
    stop("`cov_regs` must be a GRanges object.")
  }
  
  if (!is.null(mhap_obj)) {
    
    if (is.null(cpg_df)) {
      cpg_df <- mhap_obj$cpg_df
    }
    
    if (is.null(mhap_df)) {
      mhap_df <- mhap_obj$mhap
    }
  }
  
  if (is.null(cpg_df)) {
    stop("`cpg_df` is NULL. Provide either `mhap_obj$cpg_df` or `cpg_df`.")
  }
  
  cpg_df <- normalize_cpg_df(cpg_df)
  data.table::setDT(cpg_df)
  
  if (nrow(cpg_df) == 0L) {
    message("No CpG coordinates available.")
    return(GenomicRanges::GRanges())
  }
  
  # Restrict CpGs to covered regions first.
  cpg_df <- filter_cpg_by_regions(
    cpg_df = cpg_df,
    regions_gr = cov_regs
  )
  
  if (nrow(cpg_df) == 0L) {
    message("No CpG coordinates fall within `cov_regs`.")
    return(GenomicRanges::GRanges())
  }
  
  data.table::setorder(cpg_df, chr, pos)
  
  cpg_gr <- GenomicRanges::GRanges(
    seqnames = cpg_df$chr,
    ranges = IRanges::IRanges(
      start = cpg_df$pos,
      width = 1L
    )
  )
  
  chr_levels <- unique(cpg_df$chr)
  
  win_list <- vector("list", length(chr_levels))
  names(win_list) <- chr_levels
  
  for (chr_name in chr_levels) {
    
    dt_chr <- cpg_df[chr == chr_name]
    pos <- dt_chr$pos
    
    if (length(pos) == 0L) {
      next
    }
    
    left_start <- pmax(pos - window + 1L, 1L)
    left_end <- pos
    
    right_start <- pos
    right_end <- pos + window - 1L
    
    starts <- c(left_start, right_start)
    ends <- c(left_end, right_end)
    
    gr_chr <- GenomicRanges::GRanges(
      seqnames = chr_name,
      ranges = IRanges::IRanges(
        start = starts,
        end = ends
      )
    )
    
    gr_chr <- BiocGenerics::unique(gr_chr)
    
    win_list[[chr_name]] <- gr_chr
  }
  
  win_list <- win_list[!vapply(win_list, is.null, logical(1))]
  
  if (length(win_list) == 0L) {
    message("No windows generated from mHap CpG coordinates.")
    return(GenomicRanges::GRanges())
  }
  
  all_win <- do.call(c, base::unname(win_list))
  
  # Count CpGs per candidate window.
  cpg_per_win <- GenomicRanges::countOverlaps(
    all_win,
    cpg_gr,
    ignore.strand = TRUE
  )
  
  keep <- cpg_per_win >= min.C & cpg_per_win <= max.C
  
  if (!any(keep)) {
    message("No windows with CpG count in [", min.C, ", ", max.C, "].")
    return(GenomicRanges::GRanges())
  }
  
  all_win_filt <- all_win[keep]
  S4Vectors::mcols(all_win_filt)$num_cpg <- cpg_per_win[keep]
  
  # Keep only windows fully contained within covered regions.
  hits <- GenomicRanges::findOverlaps(
    all_win_filt,
    cov_regs,
    type = "within",
    ignore.strand = TRUE
  )
  
  if (length(hits) == 0L) {
    message("No windows fall completely within `cov_regs`.")
    return(GenomicRanges::GRanges())
  }
  
  contained_idx <- unique(S4Vectors::queryHits(hits))
  final_windows <- all_win_filt[contained_idx]
  
  # Optional: compute mHap-derived read counts per window.
  if (isTRUE(add_num_reads) && !is.null(mhap_df)) {
    
    num_reads <- count_mhap_reads_over_windows(
      windows_gr = final_windows,
      mhap_df = mhap_df
    )
    
    S4Vectors::mcols(final_windows)$num_reads <- num_reads
  }
  
  return(final_windows)
}

#' Count mHap reads overlapping genomic windows
#'
#' Internal helper used by `makeWindowsFromMhap()`. For each window, it sums
#' the `nreads` values of all mHap records overlapping that window.
#'
#' @param windows_gr A `GRanges` object containing genomic windows.
#' @param mhap_df A data table of mHap records with columns `chr`, `start`,
#' `end`, and `nreads`.
#'
#' @return Integer or numeric vector with one value per window.
#'
#' @keywords internal
#' @noRd
count_mhap_reads_over_windows <- function(
    windows_gr,
    mhap_df
) {
  
  data.table::setDT(mhap_df)
  
  mhap_df <- mhap_df[
    !is.na(chr) &
      !is.na(start) &
      !is.na(end) &
      start <= end &
      !is.na(nreads) &
      nreads > 0L
  ]
  
  if (nrow(mhap_df) == 0L || length(windows_gr) == 0L) {
    return(rep(0L, length(windows_gr)))
  }
  
  mhap_gr <- GenomicRanges::GRanges(
    seqnames = mhap_df$chr,
    ranges = IRanges::IRanges(
      start = mhap_df$start,
      end = mhap_df$end
    )
  )
  
  hits <- GenomicRanges::findOverlaps(
    windows_gr,
    mhap_gr,
    ignore.strand = TRUE
  )
  
  if (length(hits) == 0L) {
    return(rep(0L, length(windows_gr)))
  }
  
  read_dt <- data.table::data.table(
    win_idx = S4Vectors::queryHits(hits),
    nreads = mhap_df$nreads[S4Vectors::subjectHits(hits)]
  )
  
  read_dt <- read_dt[
    ,
    .(num_reads = sum(nreads, na.rm = TRUE)),
    by = win_idx
  ]
  
  out <- numeric(length(windows_gr))
  out[read_dt$win_idx] <- read_dt$num_reads
  
  return(out)
}
