#' Extract epiallele information directly from mHap records
#'
#' @description
#' `epiAnalysisFromMhap()` is the mHap-native counterpart of
#' `epiAnalysisFromSparse()`. For each genomic interval, the function selects
#' mHap records covering all CpGs in the interval, slices each mHap pattern to
#' the CpGs contained in the interval, aggregates identical local epialleles by
#' summing their `nreads`, and computes epiallele summary statistics directly
#' on the compressed weighted representation.
#'
#' Differently from the sparse-matrix backend, this function does not expand
#' mHap counts into one row per read. Instead, it uses weighted implementations
#' of the main epiallele statistics, where each local epiallele contributes
#' according to its `nreads` value.
#'
#' @param mhap_obj Optional list returned by `loadInputFromMhap()`, typically
#' with `output_type = "mhap"` or `output_type = "both"`. The object should
#' contain at least:
#' \describe{
#'   \item{`mhap`}{A data table of mHap records with columns `chr`, `start`,
#'   `end`, `epi`, `nreads`, and `strand`.}
#'   \item{`cpg_df`}{Target CpG coordinates used for the analysis.}
#'   \item{`cpg_df_all`}{Full CpG coordinate table used to map each mHap
#'   epiallele character to its genomic CpG position.}
#' }
#'
#' @param mhap_df Optional `data.table` or `data.frame` of mHap records.
#' Required only if `mhap_obj` is not provided.
#'
#' @param cpg_df Optional CpG coordinate table defining the target CpGs used
#' in the analysis. Required only if `mhap_obj` is not provided. The table must
#' contain columns `chr` and `pos`, or any format accepted by `normalize_cpg_df()`.
#'
#' @param cpg_df_all Optional complete CpG coordinate table used to interpret
#' the full mHap patterns. If `NULL`, `cpg_df` is used. For correct pattern
#' slicing, this should usually contain all CpGs used to generate the mHap file.
#'
#' @param bins A `GenomicRanges::GRanges` object defining the genomic intervals
#' to analyse. Typically generated by `makeWindowsFromMhap()` or
#' `makeWindowsFromSparse()`.
#'
#' @param code_map_epiallele Named integer vector mapping mHap pattern
#' characters to epiallele codes. For standard mHap files, the default maps
#' `"0"` to `0`, `"1"` to `1`, and all unexpected values to `2`.
#'
#' @param remove_ambiguous Logical. Whether local epialleles containing values
#' listed in `unknown_code` should be removed before computing summary
#' statistics. Default is `TRUE`.
#'
#' @param unknown_code Numeric vector specifying codes considered ambiguous,
#' unresolved, or unknown. Default is `c(2)`.
#'
#' @param stranded Logical. If `TRUE`, epiallele statistics are computed
#' separately for `+` and `-` strand mHap records. If `FALSE`, strand information
#' is ignored and local epialleles are merged across strands. Default is `FALSE`.
#'
#' @param threshold Integer. Minimum number of reads required for a region to be
#' analysed. The number of reads is computed as the sum of `nreads` across local
#' epialleles before ambiguous epiallele removal, matching the sparse backend
#' semantics.
#'
#' @param myfuns Named list or character vector specifying which statistics to
#' compute. Supported names in the weighted mHap backend are:
#' `"dist"`, `"epi"`, `"singleton"`, `"maxfreq"`, `"shannon"`,
#' `"mean_met"`, `"num_cg"`, and `"num_reads"`.
#' If `myfuns` is a named list, only its names are used to select the weighted
#' implementations. For `"mean_met"`, parameters can be supplied as in the
#' sparse backend, e.g.
#' `list(func = meanMeth_mod, param = list(meth_code = 1L, unmeth_code = 0L))`.
#'
#' @param sample_name Character string used to label output files.
#'
#' @param pathDir Optional output directory. If not `NULL`, three compressed
#' output files are written: intervals, epiallele composition, and log.
#'
#' @param cores Integer. Number of CPU cores used for parallel processing of
#' genomic interval chunks. Default is `1`.
#'
#' @param strict Logical. If `TRUE`, the function stops when the number of CpGs
#' inferred from `cpg_df_all` between an mHap start/end interval does not match
#' the length of the mHap pattern. If `FALSE`, inconsistent records are skipped
#' with a warning. Default is `TRUE`.
#'
#' @return A list with three elements:
#' \describe{
#'   \item{`intervals`}{A data table with one row per analysed interval and
#'   strand, containing genomic coordinates and weighted summary statistics.}
#'   \item{`epi`}{A data table containing compressed local epiallele
#'   compositions for each interval. The `Freq` column stores the summed
#'   `nreads` for each local epiallele.}
#'   \item{`log`}{A data table containing intervals that were skipped because
#'   they did not satisfy coverage requirements or had no valid local
#'   epialleles.}
#' }
#'
#' @details
#' For each interval, the function first identifies the CpGs contained in the
#' interval using `cpg_df`. It then selects mHap records overlapping the CpG
#' span and keeps only records that cover all CpGs in the interval, reproducing
#' the same logic used in the sparse backend where reads with zeros inside the
#' selected submatrix are removed.
#'
#' Each retained mHap pattern is sliced to the CpG positions inside the interval.
#' Identical sliced epialleles are then aggregated by summing `nreads`. Summary
#' statistics are computed on this compressed representation without expanding
#' counts into individual read rows.
#'
#' @examples
#' \dontrun{
#' res_mhap <- epiAnalysisFromMhap(
#'   mhap_obj = inputMhap$mhap_obj,
#'   bins = windows_mhap,
#'   code_map_epiallele = c(`0` = 0L, `1` = 1L, default = 2L),
#'   remove_ambiguous = TRUE,
#'   unknown_code = c(2),
#'   stranded = FALSE,
#'   threshold = 10,
#'   myfuns = myfuns,
#'   sample_name = "sample1",
#'   pathDir = "results/",
#'   cores = 8
#' )
#' }
#'
#' @import data.table
#' @import GenomicRanges
#' @import IRanges
#' @import S4Vectors
#' @import foreach
#' @import doParallel
#' @importFrom parallel makeCluster stopCluster
#' @export
 

epiAnalysisFromMhap <- function(
    mhap_obj = NULL,
    mhap_df = NULL,
    cpg_df = NULL,
    cpg_df_all = NULL,
    bins,
    code_map_epiallele = c(`0` = 0L, `1` = 1L, default = 2L),
    remove_ambiguous = TRUE,
    unknown_code = c(2),
    stranded = FALSE,
    threshold,
    myfuns,
    sample_name,
    pathDir = NULL,
    cores = 1,
    strict = TRUE
) {
  
  if (!methods::is(bins, "GRanges")) {
    stop("`bins` must be a GenomicRanges::GRanges object.")
  }
  
  if (!is.null(mhap_obj)) {
    if (is.null(mhap_df)) {
      mhap_df <- mhap_obj$mhap
    }
    
    if (is.null(cpg_df)) {
      cpg_df <- mhap_obj$cpg_df
    }
    
    if (is.null(cpg_df_all)) {
      cpg_df_all <- mhap_obj$cpg_df_all
    }
  }
  
  if (is.null(mhap_df)) {
    stop("`mhap_df` is NULL. Provide either `mhap_obj` or `mhap_df`.")
  }
  
  if (is.null(cpg_df)) {
    stop("`cpg_df` is NULL. Provide either `mhap_obj$cpg_df` or `cpg_df`.")
  }
  
  if (is.null(cpg_df_all)) {
    cpg_df_all <- cpg_df
  }
  
  data.table::setDT(mhap_df)
  data.table::setDT(cpg_df)
  data.table::setDT(cpg_df_all)
  
  cpg_df <- normalize_cpg_df_mhap_analysis(cpg_df)
  cpg_df_all <- normalize_cpg_df_mhap_analysis(cpg_df_all)
  
  mhap_df <- mhap_df[
    !is.na(chr) &
      !is.na(start) &
      !is.na(end) &
      start <= end &
      !is.na(epi) &
      nchar(epi) > 0L &
      !is.na(nreads) &
      nreads > 0L
  ]
  
  if (nrow(mhap_df) == 0L) {
    stop("No valid mHap records available.")
  }
  
  if (nrow(cpg_df) == 0L) {
    stop("No target CpG coordinates available.")
  }
  
  if (nrow(cpg_df_all) == 0L) {
    stop("No full CpG coordinate table available.")
  }
  
  data.table::setorder(mhap_df, chr, start, end)
  data.table::setorder(cpg_df, chr, pos)
  data.table::setorder(cpg_df_all, chr, pos)
  
  cpg_pos_by_chr <- split(cpg_df_all$pos, cpg_df_all$chr)
  
  df <- as.data.frame(bins)
  
  if (nrow(df) == 0L) {
    stop("`bins` has zero rows.")
  }
  
  if ("num_cpg" %in% colnames(df)) {
    message("Dividing region table into ", cores, " tables with balancing load...")
    
    use_reads <- "num_reads" %in% colnames(df)
    
    df_split <- makeBalancedChunksMhapAnalysis(
      df = df,
      cores = cores,
      use_reads = use_reads
    )
    
  } else {
    message("Dividing region table into ", cores, " tables by row number...")
    
    n_chunks <- min(cores, nrow(df))
    
    df_split <- split(
      df,
      cut(
        seq_len(nrow(df)),
        breaks = n_chunks,
        labels = FALSE
      )
    )
  }
  
  message("Subsetting mHap records by region chunks...")
  
  mhap_chunks <- lapply(
    df_split,
    function(dfi) {
      regions_gr <- GenomicRanges::reduce(
        GenomicRanges::makeGRangesFromDataFrame(
          dfi,
          keep.extra.columns = FALSE
        )
      )
      
      subsetMhapByRegionsForAnalysis(
        mhap_df = mhap_df,
        regions_gr = regions_gr
      )
    }
  )
  
  strand_mode <- ifelse(stranded, "stranded", "unstranded")
  
  message(
    "Extracting weighted epialleles from mHap in ",
    strand_mode,
    " mode using ",
    cores,
    " cores..."
  )
  
  if (cores > 1L) {
    
    cl <- parallel::makeCluster(cores, type = "PSOCK")
    doParallel::registerDoParallel(cl)
    
    Mapi <- tryCatch(
      {
        foreach::foreach(
          dfi = df_split,
          mhap_dfi = mhap_chunks,
          .packages = c(
            "data.table",
            "tidyverse",
            "GenomicRanges",
            "IRanges",
            "S4Vectors"
          ),
          .export = c(
            "epiallele_analyse_fromMhap",
            "extractLocalEpiallelesFromMhapBin",
            "get_cpg_between_mhap_analysis",
            "get_out_mhap",
            "subsetMhapByRegionsForAnalysis",
            "getBinCoordinatesForMhap",
            "normalize_cpg_df_mhap_analysis"
          )
        ) %dopar% {
          
          ret_list <- vector("list", nrow(dfi))
          
          for (i in seq_len(nrow(dfi))) {
            ret_list[[i]] <- epiallele_analyse_fromMhap(
              mhap_df = mhap_dfi,
              cpg_df = cpg_df,
              cpg_pos_by_chr = cpg_pos_by_chr,
              bin = dfi[i, , drop = FALSE],
              code_map_epiallele = code_map_epiallele,
              stranded = stranded,
              threshold = threshold,
              myfuns = myfuns,
              remove_ambiguous = remove_ambiguous,
              unknown_code = unknown_code,
              strict = strict
            )
          }
          
          ret_list
        }
      },
      finally = {
        try(parallel::stopCluster(cl), silent = TRUE)
        foreach::registerDoSEQ()
      }
    )
    
  } else {
    
    Mapi <- Map(
      function(dfi, mhap_dfi) {
        
        ret_list <- vector("list", nrow(dfi))
        
        for (i in seq_len(nrow(dfi))) {
          ret_list[[i]] <- epiallele_analyse_fromMhap(
            mhap_df = mhap_dfi,
            cpg_df = cpg_df,
            cpg_pos_by_chr = cpg_pos_by_chr,
            bin = dfi[i, , drop = FALSE],
            code_map_epiallele = code_map_epiallele,
            stranded = stranded,
            threshold = threshold,
            myfuns = myfuns,
            remove_ambiguous = remove_ambiguous,
            unknown_code = unknown_code,
            strict = strict
          )
        }
        
        ret_list
      },
      df_split,
      mhap_chunks
    )
  }
  
  message("Extracting results for sample ", sample_name, "...")
  
  Mapi_flat <- do.call(c, Mapi)
  
  intervals <- data.table::rbindlist(
    lapply(Mapi_flat, `[[`, "intervals"),
    use.names = TRUE,
    fill = TRUE
  )
  
  epi <- data.table::rbindlist(
    lapply(Mapi_flat, `[[`, "epi"),
    use.names = TRUE,
    fill = TRUE
  )
  
  log <- data.table::rbindlist(
    lapply(Mapi_flat, `[[`, "log"),
    use.names = TRUE,
    fill = TRUE
  )
  
  if (!is.null(pathDir)) {
    
    if (!dir.exists(pathDir)) {
      dir.create(pathDir, recursive = TRUE)
    }
    
    message("Saving results for sample ", sample_name, " in ", pathDir, " folder...")
    
    data.table::fwrite(
      intervals,
      file = file.path(pathDir, paste0(sample_name, "_intervals.bed.gz")),
      sep = "\t"
    )
    
    data.table::fwrite(
      epi,
      file = file.path(pathDir, paste0(sample_name, "_epiAnalysis.txt.gz")),
      sep = "\t"
    )
    
    data.table::fwrite(
      log,
      file = file.path(pathDir, paste0(sample_name, "_log.txt.gz")),
      sep = "\t",
      col.names = FALSE
    )
  }
  
  message("Analysis completed for ", sample_name, "!")
  
  list(
    intervals = intervals,
    epi = epi,
    log = log
  )
}


epiallele_analyse_fromMhap <- function(
    mhap_df,
    cpg_df,
    cpg_pos_by_chr,
    bin,
    code_map_epiallele = c(`0` = 0L, `1` = 1L, default = 2L),
    stranded = FALSE,
    threshold,
    myfuns,
    remove_ambiguous = TRUE,
    unknown_code = c(2),
    strict = TRUE
) {
  
  out <- list(
    intervals = data.frame(),
    epi = data.frame(),
    log = data.frame()
  )
  
  bin_info <- getBinCoordinatesForMhap(bin)
  coord <- bin_info$coord
  
  if (nrow(mhap_df) == 0L) {
    out$log <- as.data.frame(coord)
    return(out)
  }
  
  local_epi <- extractLocalEpiallelesFromMhapBin(
    mhap_df = mhap_df,
    cpg_df = cpg_df,
    cpg_pos_by_chr = cpg_pos_by_chr,
    bin = bin,
    code_map_epiallele = code_map_epiallele,
    unknown_code = unknown_code,
    strict = strict
  )
  
  if (nrow(local_epi) == 0L) {
    out$log <- as.data.frame(coord)
    return(out)
  }
  
  cpg_pos <- attr(local_epi, "cpg_pos")
  
  total_reads_before_ambiguous_filter <- sum(local_epi$nreads, na.rm = TRUE)
  
  if (total_reads_before_ambiguous_filter < threshold) {
    out$log <- as.data.frame(coord)
    return(out)
  }
  
  if (isTRUE(stranded)) {
    
    strand_levels <- unique(local_epi$strand)
    strand_levels <- strand_levels[!is.na(strand_levels)]
    
    if (length(strand_levels) == 0L) {
      out$log <- as.data.frame(coord)
      return(out)
    }
    
    produced_any <- FALSE
    
    for (strand_i in strand_levels) {
      
      local_i <- local_epi[strand == strand_i]
      
      if (remove_ambiguous) {
        local_i <- local_i[has_unknown == FALSE]
      }
      
      if (nrow(local_i) == 0L || sum(local_i$nreads, na.rm = TRUE) == 0L) {
        next
      }
      
      out_i <- get_out_mhap(
        epi_counts_dt = local_i,
        cpg_pos = cpg_pos,
        out = list(),
        strand = strand_i,
        coord = coord,
        myfuns = myfuns
      )
      
      out$epi <- rbind(out$epi, out_i$epi)
      out$intervals <- rbind(out$intervals, out_i$intervals)
      out$log <- rbind(out$log, out_i$log)
      
      produced_any <- TRUE
    }
    
    if (!produced_any) {
      out$log <- as.data.frame(coord)
    }
    
  } else {
    
    if (remove_ambiguous) {
      local_epi <- local_epi[has_unknown == FALSE]
    }
    
    if (nrow(local_epi) == 0L || sum(local_epi$nreads, na.rm = TRUE) == 0L) {
      out$log <- as.data.frame(coord)
      return(out)
    }
    
    local_epi <- local_epi[
      ,
      .(
        nreads = sum(nreads, na.rm = TRUE),
        has_unknown = any(has_unknown),
        n_cpg = unique(n_cpg)[1]
      ),
      by = epi
    ]
    
    local_epi[, strand := "*"]
    
    out <- get_out_mhap(
      epi_counts_dt = local_epi,
      cpg_pos = cpg_pos,
      out = out,
      strand = "*",
      coord = coord,
      myfuns = myfuns
    )
  }
  
  out
}


extractLocalEpiallelesFromMhapBin <- function(
    mhap_df,
    cpg_df,
    cpg_pos_by_chr,
    bin,
    code_map_epiallele = c(`0` = 0L, `1` = 1L, default = 2L),
    unknown_code = c(2),
    strict = TRUE
) {
  
  data.table::setDT(mhap_df)
  data.table::setDT(cpg_df)
  
  bin_info <- getBinCoordinatesForMhap(bin)
  
  chr_i <- bin_info$chr
  start_i <- bin_info$start
  end_i <- bin_info$end
  
  cpg_bin <- cpg_df[
    chr == chr_i &
      pos >= start_i &
      pos <= end_i
  ]
  
  if (nrow(cpg_bin) == 0L) {
    return(data.table::data.table())
  }
  
  data.table::setorder(cpg_bin, pos)
  
  cpg_bin_pos <- cpg_bin$pos
  
  mhap_bin <- mhap_df[
    chr == chr_i &
      end >= min(cpg_bin_pos) &
      start <= max(cpg_bin_pos)
  ]
  
  if (nrow(mhap_bin) == 0L) {
    return(data.table::data.table())
  }
  
  if (!chr_i %in% names(cpg_pos_by_chr)) {
    return(data.table::data.table())
  }
  
  pos_vec_chr <- cpg_pos_by_chr[[chr_i]]
  
  default_code <- base::unname(code_map_epiallele["default"])
  
  if (is.na(default_code)) {
    default_code <- NA_integer_
  }
  
  out_list <- vector("list", nrow(mhap_bin))
  out_idx <- 0L
  
  for (k in seq_len(nrow(mhap_bin))) {
    
    start_k <- mhap_bin$start[k]
    end_k <- mhap_bin$end[k]
    epi_k <- mhap_bin$epi[k]
    nreads_k <- as.integer(mhap_bin$nreads[k])
    strand_k <- mhap_bin$strand[k]
    
    if (is.na(nreads_k) || nreads_k <= 0L) {
      next
    }
    
    pattern_vec <- strsplit(epi_k, "", fixed = TRUE)[[1]]
    
    full_cpg_pos <- get_cpg_between_mhap_analysis(
      pos_vec = pos_vec_chr,
      start = start_k,
      end = end_k
    )
    
    if (length(full_cpg_pos) != length(pattern_vec)) {
      
      msg <- paste0(
        "mHap pattern length does not match number of CpGs for record ",
        k,
        " (", chr_i, ":", start_k, "-", end_k, "). ",
        "nchar(epi) = ", length(pattern_vec),
        "; n CpGs = ", length(full_cpg_pos), "."
      )
      
      if (strict) {
        stop(msg)
      } else {
        warning(msg)
        next
      }
    }
    
    idx <- match(cpg_bin_pos, full_cpg_pos)
    
    if (any(is.na(idx))) {
      next
    }
    
    local_chars <- pattern_vec[idx]
    
    local_vals <- base::unname(code_map_epiallele[local_chars])
    
    if (any(is.na(local_vals))) {
      
      if (is.na(default_code)) {
        
        msg <- paste0(
          "Some mHap pattern characters do not appear in `code_map_epiallele`: ",
          paste(unique(local_chars[is.na(local_vals)]), collapse = ", ")
        )
        
        if (strict) {
          stop(msg)
        } else {
          warning(msg)
          next
        }
        
      } else {
        local_vals[is.na(local_vals)] <- default_code
      }
    }
    
    local_vals <- as.integer(local_vals)
    
    strand_k <- as.character(strand_k)
    
    if (!strand_k %in% c("+", "-")) {
      strand_k <- "*"
    }
    
    out_idx <- out_idx + 1L
    
    out_list[[out_idx]] <- data.table::data.table(
      epi = paste(local_vals, collapse = ""),
      nreads = nreads_k,
      strand = strand_k,
      n_cpg = length(local_vals),
      has_unknown = any(local_vals %in% unknown_code)
    )
  }
  
  if (out_idx == 0L) {
    return(data.table::data.table())
  }
  
  out_list <- out_list[seq_len(out_idx)]
  
  local_epi <- data.table::rbindlist(out_list, use.names = TRUE, fill = TRUE)
  
  local_epi <- local_epi[
    ,
    .(
      nreads = sum(nreads, na.rm = TRUE),
      has_unknown = any(has_unknown),
      n_cpg = unique(n_cpg)[1]
    ),
    by = .(epi, strand)
  ]
  
  attr(local_epi, "cpg_pos") <- cpg_bin_pos
  
  local_epi
}


get_out_mhap <- function(
    epi_counts_dt,
    cpg_pos,
    out,
    strand,
    coord,
    myfuns
) {
  
  epi_counts_list <- list(epi = epi_counts_dt, cpg_pos = cpg_pos)

  parameters=lapply(myfuns, function(x) { 
    ifelse(length(x) == 1, x(epi_counts_list), x[[1]](epi_counts_list, x[[2]]) )
  }
  )
  
  
  param_df <- as.data.frame(
    as.list(
      sapply(
        parameters,
        function(x) {
          if (length(x) > 1L) {
            paste(x, collapse = ",")
          } else {
            x
          }
        }
      )
    )
  )
  
  mydata <- data.frame(
    as.data.frame(coord),
    param_df
  )
  
  mydata$strand <- strand
  
  out[["intervals"]] <- mydata
  
  id <- apply(
    mydata[1, c(1:3), drop = FALSE],
    1,
    function(x) paste(x, collapse = "_")
  )
  
  epi_out <- epi_counts_dt[
    ,
    .(
      Freq = sum(nreads, na.rm = TRUE)
    ),
    by = epi
  ]
  
  epi_out$id <- id
  epi_out$strand <- strand
  
  out[["epi"]] <- as.data.frame(epi_out)
  
  if (is.null(out[["log"]])) {
    out[["log"]] <- data.frame()
  }
  
  out
}


subsetMhapByRegionsForAnalysis <- function(
    mhap_df,
    regions_gr
) {
  
  if (is.null(regions_gr)) {
    return(mhap_df)
  }
  
  data.table::setDT(mhap_df)
  
  if (nrow(mhap_df) == 0L) {
    return(mhap_df)
  }
  
  mhap_gr <- GenomicRanges::GRanges(
    seqnames = mhap_df$chr,
    ranges = IRanges::IRanges(
      start = mhap_df$start,
      end = mhap_df$end
    )
  )
  
  ov <- GenomicRanges::findOverlaps(
    mhap_gr,
    regions_gr,
    ignore.strand = TRUE
  )
  
  if (length(ov) == 0L) {
    return(mhap_df[0])
  }
  
  mhap_df[unique(S4Vectors::queryHits(ov))]
}


getBinCoordinatesForMhap <- function(bin) {
  
  bin_df <- as.data.frame(bin)
  
  chr_col <- NULL
  
  if ("seqnames" %in% colnames(bin_df)) {
    chr_col <- "seqnames"
  } else if ("chr" %in% colnames(bin_df)) {
    chr_col <- "chr"
  } else {
    chr_col <- colnames(bin_df)[1]
  }
  
  if (!"start" %in% colnames(bin_df)) {
    stop("`bin` must contain a `start` column.")
  }
  
  if (!"end" %in% colnames(bin_df)) {
    stop("`bin` must contain an `end` column.")
  }
  
  list(
    chr = as.character(bin_df[[chr_col]][1]),
    start = as.integer(bin_df$start[1]),
    end = as.integer(bin_df$end[1]),
    coord = bin_df[, c(chr_col, "start", "end"), drop = FALSE]
  )
}


get_cpg_between_mhap_analysis <- function(
    pos_vec,
    start,
    end
) {
  
  if (length(pos_vec) == 0L) {
    return(integer(0))
  }
  
  lo <- findInterval(start - 1L, pos_vec) + 1L
  hi <- findInterval(end, pos_vec)
  
  if (lo > hi) {
    return(integer(0))
  }
  
  pos_vec[lo:hi]
}


normalize_cpg_df_mhap_analysis <- function(cpg_df) {
  
  data.table::setDT(cpg_df)
  
  if (all(c("chr", "pos") %in% names(cpg_df))) {
    
    out <- cpg_df[
      ,
      .(
        chr = as.character(chr),
        pos = as.integer(pos)
      )
    ]
    
  } else if (all(c("chr", "ref_pos") %in% names(cpg_df))) {
    
    out <- cpg_df[
      ,
      .(
        chr = as.character(chr),
        pos = as.integer(ref_pos)
      )
    ]
    
  } else if (all(c("seqnames", "pos") %in% names(cpg_df))) {
    
    out <- cpg_df[
      ,
      .(
        chr = as.character(seqnames),
        pos = as.integer(pos)
      )
    ]
    
  } else if (all(c("chr", "start") %in% names(cpg_df))) {
    
    out <- cpg_df[
      ,
      .(
        chr = as.character(chr),
        pos = as.integer(start)
      )
    ]
    
  } else {
    
    stop(
      "Cannot infer CpG coordinate columns. ",
      "Expected chr/pos, chr/ref_pos, seqnames/pos, or chr/start."
    )
  }
  
  out <- out[!is.na(chr) & !is.na(pos)]
  out <- unique(out)
  
  data.table::setorder(out, chr, pos)
  
  out
}


makeBalancedChunksMhapAnalysis <- function(
    df,
    cores = 1L,
    use_reads = TRUE
) {
  
  stopifnot(cores >= 1L)
  
  if (!"num_cpg" %in% colnames(df)) {
    n_chunks <- min(cores, nrow(df))
    
    return(
      split(
        df,
        cut(
          seq_len(nrow(df)),
          breaks = n_chunks,
          labels = FALSE
        )
      )
    )
  }
  
  num_cpg <- as.numeric(df$num_cpg)
  
  num_reads <- if (use_reads && "num_reads" %in% colnames(df)) {
    as.numeric(df$num_reads)
  } else {
    rep(1, nrow(df))
  }
  
  df$cost <- num_cpg * num_reads
  df$cost[is.na(df$cost)] <- 0
  
  ord <- order(df$cost, decreasing = TRUE)
  
  chunk_loads <- numeric(cores)
  chunk_id <- integer(nrow(df))
  
  for (k in ord) {
    j <- which.min(chunk_loads)
    chunk_id[k] <- j
    chunk_loads[j] <- chunk_loads[j] + df$cost[k]
  }
  
  df$chunk <- chunk_id
  
  message("Chunk loads per CPU:")
  
  for (i in seq_along(chunk_loads)) {
    message(
      "  CPU ",
      i,
      ": ",
      chunk_loads[i],
      " loads and ",
      sum(df$chunk == i),
      " regions"
    )
  }
  
  split(df, df$chunk)
}