#' Extracting epiallele information from customised target regions.
#'
#' @description
#' This function takes a user-defined set of genomic regions (in the form of a 
#' GRanges object) and extracts, for each interval, the epiallele composition and 
#' summary statistics such as average methylation, Shannon entropy, epiallele 
#' diversity, etc.
#'
#' The function works on the sparse matrix generated by `loadInputONT()`, where 
#' rows correspond to reads and columns correspond to genomic positions. For each 
#' region, the corresponding submatrix is extracted, optionally separated by 
#' strand, converted to binary epialleles, and summarised.
#'
#' @importFrom foreach foreach %do% %dopar%
#' @importFrom Biostrings vmatchPattern matchPattern reverseComplement DNAString strsplit
#' @importFrom IRanges IRanges subsetByOverlaps
#' @importFrom magrittr %>%
#' @importFrom parallel makeCluster stopCluster
#' @importFrom doParallel registerDoParallel
#' @import data.table 
#' @param sparseMat 
#' A sparse matrix (dgCMatrix) generated by `loadInputONT()`, where rows are reads 
#' and columns are genomic motif positions (e.g. CpGs) encoded as `"chr_pos"`.
#' @param bins 
#' A `GRanges` object defining the target genomic intervals. Typically generated 
#' using `makeWindows()` or `makeBins()`.
#' @param read_attr_df Optional \code{data.frame} or \code{data.table}
#'   containing read-level attributes to be summarized for each genomic bin.
#'   The table must contain a read identifier column named either
#'   \code{readID} or \code{read_id}, matching the row names of
#'   \code{sparseMat}. Additional columns specified by \code{read_attr_cols}
#'   are expected to be logical or coercible to logical values. For each bin,
#'   the function counts how many reads used to build the complete epiallele
#'   patterns carry each selected attribute. If \code{NULL}, no read-level
#'   attribute summary is added. Default is \code{NULL}.
#' @param read_attr_cols Optional character vector specifying which columns of
#'   \code{read_attr_df} should be summarized per bin. Each selected column is
#'   interpreted as a boolean read-level attribute. For example, when using the
#'   output of \code{markReadsWithMutations()}, this can be
#'   \code{c("SNPevent", "INS", "DEL")}. The output interval table will contain
#'   one additional column per selected attribute, named
#'   \code{num_reads_<attribute>}, reporting the number of reads carrying that
#'   attribute among the reads retained for epiallele construction in the bin.
#'   If \code{read_attr_df} is provided and \code{read_attr_cols = NULL}, the
#'   default attributes \code{c("SNPevent", "INS", "DEL")} are used.
#' @param code_map_epiallele 
#' Named integer vector defining how the sparse matrix values (e.g. 1, 2, 3) 
#' should be converted into binary epialleles (e.g. unmethylated = 0, methylated = 1).
#' @param remove_ambiguous 
#' Logical value indicating whether rows containing ambiguous or unresolved 
#' epiallele codes should be removed from the epiallele matrix. 
#' If `TRUE`, all rows in `epi_mat` containing at least one value included 
#' in `unknown_code` are discarded. If `FALSE`, no filtering based on ambiguous 
#' codes is applied. Default is `TRUE`.
#' @param unknown_code 
#' Numeric vector specifying the code values that should be considered ambiguous, 
#' unresolved, or unknown. These values are used only when `remove_ambiguous = TRUE`. 
#' Any row of `epi_mat` containing at least one value present in 
#' `unknown_code` will be removed. Default is `c(2)`.
#' @param stranded 
#' Logical indicating whether the analysis should be performed in strand-specific 
#' mode (`TRUE`) or by merging both strands (`FALSE`). Default: `FALSE`.
#' @param threshold 
#' Minimum number of reads required for a region to be analysed. Regions with 
#' total coverage below this threshold are discarded and reported in the log.
#' @param myfuns 
#' A named list of functions to compute summary statistics on the binary 
#' epiallele matrix (e.g. mean methylation, Shannon entropy, number of epialleles).
#' @param sample_name 
#' Character string indicating the sample name used for labelling outputs.
#' @param pathDir 
#' Directory in which results will be saved. If `NULL`, results are returned but 
#' not written to disk.
#' @param cores 
#' Integer specifying the number of CPU cores used for parallel processing.
#' @return 
#' A list with the following components:
#' \itemize{
#'   \item **intervals** — Data frame where each row corresponds to a processed 
#'   genomic region, containing summary statistics produced by `myfuns`.
#'
#'   \item **epi** — Data frame containing compressed epiallele composition for 
#'   each region (e.g. epiallele sequences and their frequencies).
#'
#'   \item **log** — Data frame listing genomic intervals that did not satisfy 
#'   minimum coverage requirements or were otherwise excluded.
#' }
#' @export


epiAnalysisFromSparse= function(
    sparseMat,
    bins,
    read_attr_df = NULL,
    read_attr_cols = NULL,
    code_map_epiallele = c(`1`= 2, `2` = 0, `3`= 1, `4`= 0),
    remove_ambiguous = TRUE,
    unknown_code=c(2),
    stranded=FALSE,
    threshold,
    myfuns,
    sample_name,
    pathDir,
    cores = 1)
{
  
  if (!methods::is(sparseMat, "dgCMatrix")) {
    stop("Input must be a sparse dgCMatrix")
  }
  
  values <- abs(sparseMat@x)
  uniq_vals <- sort(unique(values))
  
  if (!all(as.character(uniq_vals) %in% names(code_map_epiallele))) {
    stop("Some matrix values do not appear in `code_map_epiallele`.\n",
         "Missing: ", paste(base::setdiff(as.character(uniq_vals),
                                    names(code_map_epiallele)), collapse=", "))
  }
  
  read_id_col <- NULL
  
  if (!is.null(read_attr_df)) {
    
    if (is.null(rownames(sparseMat))) {
      stop(
        "`read_attr_df` was provided, but `sparseMat` has no rownames. ",
        "Rownames of `sparseMat` must correspond to read IDs."
      )
    }
    
    if (is.null(read_attr_cols)) {
      read_attr_cols <- c("SNP", "INS", "DEL")
    }
    
    read_id_col <- if ("readID" %in% colnames(read_attr_df)) {
      "readID"
    } else if ("read_id" %in% colnames(read_attr_df)) {
      "read_id"
    } else {
      stop(
        "`read_attr_df` must contain a read ID column named `readID` or `read_id`."
      )
    }
    
    missing_read_attr_cols <- base::setdiff(read_attr_cols, colnames(read_attr_df))
    
    if (length(missing_read_attr_cols) > 0L) {
      stop(
        "The following `read_attr_cols` are not present in `read_attr_df`: ",
        paste(missing_read_attr_cols, collapse = ", "),
        "\nAvailable columns are: ",
        paste(colnames(read_attr_df), collapse = ", ")
      )
    }
  }
  
  df <- data.frame(bins)
  base_gr <- prepareSparseIndex(sparseMat)
  
  if ("num_cpg" %in% colnames(df)){
    message('Dividing region table into ', cores, ' tables with balancing load...')
    use_reads <- ifelse("num_reads" %in% colnames(df), TRUE, FALSE)
    df_split <- makeBalancedChunks(df = df, cores = cores, use_reads = use_reads)
    
  } else {
    message('Dividing region table into ', cores, ' tables with ~', round(nrow(df)/cores), ' rows...')
    df_split <- split(df, (seq(nrow(df))-1) %/% (nrow(df)/cores))
  }
  
  message('Dividing input sparseMat into ', cores, ' sparse matrices...')
  idx <- 0
  regs <- foreach::foreach (dfi = df_split) %do% {
    idx <- idx + 1
    message("Processing chunk ", idx, "/", length(df_split))
    regions_gr <- GenomicRanges::reduce(GenomicRanges::makeGRangesFromDataFrame(dfi))
    subsetSparseByRegions(sparseMat, base_gr, regions_gr)
  }
  
  
  read_attr_split <- vector("list", length(regs))
  if (!is.null(read_attr_df)) {
    message("Preparing read-level attribute table...")
    
    if (is.null(read_attr_cols)) {
      read_attr_cols <- c("SNP", "INS", "DEL")
    }
    
    read_attr_df <- .prepareReadAttrDf(
      read_attr_df = read_attr_df,
      read_id_col = "readID",
      read_attr_cols = read_attr_cols
    )
    
    data.table::setDT(read_attr_df)
    data.table::setkey(read_attr_df, readID)
    
    read_attr_split <- foreach::foreach(mat = regs) %do% {
      read_ids_chunk <- unique(rownames(mat))
      
      if (is.null(read_ids_chunk) || length(read_ids_chunk) == 0L) {
        return(NULL)
      }
      
      read_attr_df[
        list(read_ids_chunk),
        nomatch = 0L
      ]
    }
    
  } else {
    
    read_attr_split <- rep(
      list(NULL),
      length(regs)
    )
  }
  
  strand_mode <- ifelse(stranded, 'stranded', 'unstranded')
  message('Extracting epialleles in ', strand_mode, ' mode using ', cores, ' cores...')
  cl <- parallel::makeCluster(cores, type = 'PSOCK')
  doParallel::registerDoParallel(cl)
  Mapi = tryCatch(
    {
      foreach::foreach(
        dfi = df_split,
        sparseMati = regs,
        attri = read_attr_split,
        .packages = c("Matrix","GenomicRanges","IRanges","data.table", "magrittr"),
        .export   = c("epiallele_analyse_fromSparse", "prepareSparseIndex",
                      "encodeEpiallele", "get_out_mod", "subsetSparseByRegions",
                      ".summariseReadAttrsForRegion", ".addReadAttrSummaryToOut"
                      )
      ) %dopar% {
        sparseMati_gr <- prepareSparseIndex(sparseMati)
        ret_list <- vector("list", nrow(dfi))
        for (i in seq_len(nrow(dfi))) {
          ret_list[[i]] <- epiallele_analyse_fromSparse(
            sparseMati        = sparseMati,
            sparseMati_gr     = sparseMati_gr,
            bin               = dfi[i, 1:3],
            read_attr_df      = attri,
            read_attr_cols     = read_attr_cols,
            code_map_epiallele = code_map_epiallele,
            stranded          = stranded,
            threshold         = threshold,
            myfuns            = myfuns,
            remove_ambiguous = remove_ambiguous,
            unknown_code = unknown_code
          )
        }
        ret_list
      }
    },
    finally = {
      parallel::stopCluster(cl)
      foreach::registerDoSEQ()  
    }
  )
  
  message('Extracting results for sample ', sample_name, '...')
  Mapi_flat <- do.call(c, Mapi)
  intervals <- data.table::rbindlist(lapply(Mapi_flat, `[[`, "intervals"), use.names = TRUE, fill = TRUE)
  epi       <- data.table::rbindlist(lapply(Mapi_flat, `[[`, "epi"),       use.names = TRUE, fill = TRUE)
  log       <- data.table::rbindlist(lapply(Mapi_flat, `[[`, "log"),       use.names = TRUE, fill = TRUE)
  
  
  message('Saving results for sample ', sample_name, ' in' , pathDir,  ' folder...')
  
  data.table::fwrite(intervals,
                     file = file.path(pathDir, paste0(sample_name, "_intervals.bed.gz")),
                     sep = "\t")
  
  data.table::fwrite(epi,
                     file = file.path(pathDir, paste0(sample_name, "_epiAnalysis.txt.gz")),
                     sep = "\t")
  
  data.table::fwrite(log,
                     file = file.path(pathDir, paste0(sample_name, "_log.txt.gz")),
                     sep = "\t",
                     col.names = FALSE)
  
  message('Analysis completed for', sample_name, '!')
  
  return(list('intervals' = intervals,
              'epi' = epi,
              'log' = log))
}


makeBalancedChunks <- function(df, cores = 1L, 
                               use_reads = TRUE) {
  stopifnot(cores >= 1L)
  
  if (!"num_cpg" %in% colnames(df)) {
    stop("mcols(bins) must contain a 'num_cpg' column.")
  }
  
  num_cpg   <- as.numeric(df$num_cpg)
  num_reads <- if (use_reads && "num_reads" %in% colnames(df)) {
    as.numeric(df$num_reads)
  } else {
    rep(1, nrow(df))  # fallback: solo num_cpg
  }
  
  df <- df %>% mutate(cost = num_cpg * num_reads) 
  df[is.na(df$cost), 'cost'] <- 0
  
  # Ordina per costo decrescente (first-fit decreasing → bilanciamento migliore)
  ord <- order(df$cost, decreasing = TRUE)
  
  chunk_loads <- numeric(cores)       # carico totale per ciascun core
  chunk_id    <- integer(nrow(df))    # a quale core appartiene ogni riga
  
  for (k in ord) {
    j <- which.min(chunk_loads)       # core meno carico al momento
    chunk_id[k] <- j
    chunk_loads[j] <- chunk_loads[j] + df$cost[k]
  }
  
  df$chunk <- chunk_id
  
  message("Chunk loads per CPU:")
  for (i in seq_along(chunk_loads)) {
    message("  CPU ", i, ": ", chunk_loads[i], ' loads and ', sum(df$chunk == i), ' regions')
  }
  
  return(split(df, df$chunk))
}


prepareSparseIndex <- function(sparseMat) {
  parts <- data.table::tstrsplit(colnames(sparseMat), "_", fixed = TRUE)
  chr_vec <- parts[[1]]
  pos_vec <- as.integer(parts[[2]])
  
  GenomicRanges::GRanges(seqnames = chr_vec, ranges = IRanges(pos_vec, width = 1))
}


subsetSparseByRegions <- function(sparseMat, base_gr, regions) {
  
  if(is.data.frame(regions))
    regions_gr <- GenomicRanges::makeGRangesFromDataFrame(regions, keep.extra.columns = FALSE)
  else
    regions_gr <- regions
  
  # colonne che cadono nelle regioni
  ov <- GenomicRanges::findOverlaps(base_gr, regions_gr, ignore.strand = TRUE)
  cols_keep <- sort(unique(S4Vectors::queryHits(ov)))
  
  if (length(cols_keep) == 0L) {
    warning("Any column of your matrix falls into the selected regions.")
    return(sparseMat[, 0, drop = FALSE])
  }
  
  f_sparseMat <- sparseMat[, cols_keep, drop = FALSE]
  
  nonzero_rows <- Matrix::rowSums(f_sparseMat != 0) > 0
  final_sparseMat <- f_sparseMat[nonzero_rows, , drop = FALSE]
  
  return(final_sparseMat)
}


epiallele_analyse_fromSparse <- function(
    sparseMati,
    sparseMati_gr,
    bin,
    read_attr_df   = NULL,
    read_attr_cols = NULL,
    code_map_epiallele,
    stranded,
    threshold,
    myfuns,
    remove_ambiguous = TRUE,
    unknown_code=c(2)
    ){
  
  out=list("intervals"=data.frame(),"epi"=data.frame(),"log"=data.frame())
  
  if (!methods::is(sparseMati, "dgCMatrix")) {
    stop("`sparseMati` must be a Matrix::dgCMatrix object.")
  }
  if (nrow(sparseMati) == 0L || ncol(sparseMati) == 0L) {
    out$log <- rbind(out$log, as.data.frame(bin))
    return(out)
  }
  
  sparseMati_in_bin <- subsetSparseByRegions(sparseMati, sparseMati_gr, bin)
  
  ## Remove reads that contain zeros --> cannot determine full pattern
  f_sparseMati_in_bin <- sparseMati_in_bin[Matrix::rowSums(sparseMati_in_bin == 0) == 0, , drop = FALSE]
  
  if (nrow(f_sparseMati_in_bin) < threshold) {
    out$log <- as.data.frame(bin)
    return(out)
  }
  
  ## ---------------------------
  ## STRANDED MODE
  ## ---------------------------
  if (stranded){
    
    ## Separate + and -
    sparseMati_plus <- f_sparseMati_in_bin[Matrix::rowSums(f_sparseMati_in_bin) > 0, , drop = FALSE]
    sparseMati_minus <- abs(f_sparseMati_in_bin[Matrix::rowSums(f_sparseMati_in_bin) < 0, , drop = FALSE]) 
    
    if (nrow(sparseMati_plus) == 0 & nrow(sparseMati_minus) == 0) {
      out$log <- as.data.frame(bin)
      return(out)
    }
    
    ## ---- PLUS STRAND ----
    if (nrow(sparseMati_plus) > 0) {
      epi_mat_plus <- encodeEpiallele(sparseMati_plus, code_map_epiallele)
      colnames(epi_mat_plus) <- as.numeric(sub(".*_", "", colnames(epi_mat_plus)))
      
      if (remove_ambiguous) {
        epi_mat_plus <- epi_mat_plus[!apply(epi_mat_plus, 1, function(x) any(x %in% unknown_code)), ]
        
        if (nrow(epi_mat_plus) == 0 ) {
          out$log <- as.data.frame(bin)
          return(out)
        }
      }
      
      out_plus <- get_out_mod(epi_mat_plus, out = list(), strand="+", coord=bin, myfuns)
      
      if (!is.null(read_attr_df)){
        read_ids_plus <- rownames(epi_mat_plus)
        out_plus <- .addReadAttrSummaryToOut(
          out = out_plus,
          read_ids = read_ids_plus,
          read_attr_df = read_attr_df ,
          read_attr_cols = read_attr_cols
        )
      }
      
      out$epi       <- rbind(out$epi, out_plus$epi)
      out$intervals <- rbind(out$intervals, out_plus$intervals)
      out$log       <- rbind(out$log, out_plus$log)
    }
    
    ## ---- MINUS STRAND ----
    if (nrow(sparseMati_minus) > 0) {
      epi_mat_minus <- encodeEpiallele(sparseMati_minus, code_map_epiallele)
      colnames(epi_mat_minus) <- as.numeric(sub(".*_", "", colnames(epi_mat_minus)))
      
      if (remove_ambiguous) {
        epi_mat_minus <- epi_mat_minus[!apply(epi_mat_minus, 1, function(x) any(x %in% unknown_code)), ]
        
        if (nrow(epi_mat_minus) == 0 ) {
          out$log <- as.data.frame(bin)
          return(out)
        }
      }
      
      out_minus <- get_out_mod(epi_mat_minus, out = list(), strand="-", coord=bin, myfuns)
      
      if (!is.null(read_attr_df )){
        read_ids_minus <- rownames(epi_mat_minus)
        out_minus <- .addReadAttrSummaryToOut(
          out = out_minus,
          read_ids = read_ids_minus,
          read_attr_df = read_attr_df,
          read_attr_cols = read_attr_cols
        )
      }
      
      out$epi       <- rbind(out$epi, out_minus$epi)
      out$intervals <- rbind(out$intervals, out_minus$intervals)
      out$log       <- rbind(out$log, out_minus$log)
      
    }
    
  } else {
    ## ---------------------------
    ## NON–STRANDED MODE
    ## ---------------------------  
    sparseMati_both <- abs(f_sparseMati_in_bin)
    
    epi_mat_both <- encodeEpiallele(sparseMat = sparseMati_both,
                                    code_map_epiallele = code_map_epiallele)
    colnames(epi_mat_both) <- as.numeric(sub(".*_", "", colnames(epi_mat_both)))
    
    if (remove_ambiguous) {
      epi_mat_both <- epi_mat_both[!apply(epi_mat_both, 1, function(x) any(x %in% unknown_code)), ]
      
      if (nrow(epi_mat_both) == 0 ) {
        out$log <- as.data.frame(bin)
        return(out)
      }
    }
    
    out <- get_out_mod(epi_df = epi_mat_both, out = out, strand = "*", coord = bin, myfuns = myfuns)
    
    if (!is.null(read_attr_df )){
      read_ids_both <- rownames(epi_mat_both)
      out <- .addReadAttrSummaryToOut(
        out = out,
        read_ids = read_ids_both,
        read_attr_df = read_attr_df ,
        read_attr_cols = read_attr_cols
      )
    }
  }
  
  return(out)
}


encodeEpiallele <- function(sparseMat,
                            code_map_epiallele = c(`1` = 2, `2` = 1, `3` = 0)) {
  
  if (!methods::is(sparseMat, "dgCMatrix")) {
    stop("Input must be a sparse dgCMatrix")
  }
  
  values <- sparseMat@x
  uniq_vals <- sort(unique(values))
  
  if (!all(as.character(uniq_vals) %in% names(code_map_epiallele))) {
    stop("Some matrix values do not appear in `code_map_epiallele`.\n",
         "Missing: ", paste(base::setdiff(as.character(uniq_vals),
                                    names(code_map_epiallele)), collapse=", "))
  }
  
  # Ricodifica 
  new_vals <- as.numeric(code_map_epiallele[as.character(values)])
  
  newMat <- sparseMat
  newMat@x <- new_vals
  
  methods::validObject(newMat)  
  
  newMat_dense <- as.matrix(newMat)
  newMat_df <- as.data.frame(newMat_dense)
  
  return(newMat_df)
}


get_out_mod=function(epi_df, out, strand, coord, myfuns)
{
 
  parameters <- lapply(myfuns, function(fun_spec) {
    
    if (is.function(fun_spec)) {
      
      fun_spec(epi_df)
      
    } else if (
      is.list(fun_spec) &&
      length(fun_spec) >= 2L &&
      is.function(fun_spec[[1]])
    ) {
      
      fun_spec[[1]](epi_df, fun_spec[[2]])
      
    } else {
      
      stop(
        "Each element of `myfuns` must be either a function ",
        "or a list where the first element is a function and the second is a parameter."
      )
    }
  })
  
  param_df <- as.data.frame(as.list(sapply(parameters, function(x) {
    if (length(x) > 1) paste(x, collapse = ",") else x
  })))
  
  mydata = data.frame(as.data.frame(coord), param_df)
  mydata$strand = strand
  
  out[["intervals"]] = mydata
  
  id = apply(mydata[1,c(1:3)], 1 , function(x) paste(x,collapse="_"))
  epi_df$epi = apply(epi_df, 1, function(x) paste(x, collapse = ""))
  epi_df = as.data.frame(table(epi_df$epi)) %>% dplyr::rename('epi' = 'Var1')
  epi_df$id = id
  epi_df$strand = strand
  
  out[["epi"]] = epi_df
  
  return(out)
}


.addReadAttrSummaryToOut <- function(
    out,
    read_ids,
    read_attr_df = NULL,
    read_attr_cols = c("SNP", "INS", "DEL")
) {
  
  if (is.null(read_attr_df)) {
    return(out)
  }
  
  if (is.null(out[["intervals"]]) || nrow(out[["intervals"]]) == 0L) {
    return(out)
  }
  
  attr_summary <- .summariseReadAttrsForRegion(
    read_ids = read_ids,
    read_attr_df = read_attr_df,
    read_attr_cols = read_attr_cols
  )
  
  if (ncol(attr_summary) == 0L) {
    return(out)
  }
  
  for (cc in colnames(attr_summary)) {
    out[["intervals"]][[cc]] <- attr_summary[[cc]]
  }
  
  return(out)
}

.summariseReadAttrsForRegion <- function(
    read_ids,
    read_attr_df = NULL,
    read_attr_cols = c("SNP", "INS", "DEL")
) {
  
  if (is.null(read_attr_df)) {
    return(data.frame())
  }
  
  requireNamespace("data.table")
  
  read_ids <- unique(as.character(read_ids))
  read_ids <- read_ids[!is.na(read_ids)]
  
  out_names <- paste0("num_reads_", read_attr_cols)
  
  if (length(read_ids) == 0L) {
    out <- as.list(rep(0L, length(read_attr_cols)))
    names(out) <- out_names
    return(as.data.frame(out))
  }
  
  dt <- data.table::as.data.table(read_attr_df)
  
  x <- dt[
    readID %in% read_ids
  ]
  
  counts <- vapply(
    read_attr_cols,
    function(cc) {
      if (!cc %in% colnames(x)) {
        return(0L)
      }
      sum(as.logical(x[[cc]]), na.rm = TRUE)
    },
    integer(1)
  )
  
  names(counts) <- out_names
  
  counts_df <- as.data.frame(as.list(counts))
  return(counts_df)
}


.prepareReadAttrDf <- function(
    read_attr_df,
    read_id_col = "readID",
    read_attr_cols = c("SNP", "INS", "DEL")
) {
  
  if (is.null(read_attr_df)) {
    return(NULL)
  }
  
  requireNamespace("data.table")
  
  dt <- data.table::as.data.table(read_attr_df)
  
  if (!read_id_col %in% colnames(dt)) {
    if ("read_id" %in% colnames(dt)) {
      read_id_col <- "read_id"
    } else {
      stop(
        "`read_attr_df` must contain a read ID column named `",
        read_id_col,
        "` or `read_id`."
      )
    }
  }
  
  missing_cols <- base::setdiff(read_attr_cols, colnames(dt))
  
  if (length(missing_cols) > 0L) {
    stop(
      "Missing columns in `read_attr_df`: ",
      paste(missing_cols, collapse = ", ")
    )
  }
  
  dt <- dt[
    ,
    c(read_id_col, read_attr_cols),
    with = FALSE
  ]
  
  data.table::setnames(dt, read_id_col, "readID")
  
  dt[, readID := as.character(readID)]
  
  for (cc in read_attr_cols) {
    
    if (is.logical(dt[[cc]])) {
      next
    }
    
    if (is.numeric(dt[[cc]]) | is.integer(dt[[cc]])) {
      dt[, (cc) := !is.na(get(cc)) & get(cc) != 0]
    } else {
      dt[
        ,
        (cc) := tolower(trimws(as.character(get(cc)))) %in%
          c("true", "t", "1", "yes", "y")
      ]
    }
  }
  
  # Se ci sono più righe per read, collasso con any().
  dt <- dt[
    ,
    lapply(.SD, function(x) any(x, na.rm = TRUE)),
    by = readID,
    .SDcols = read_attr_cols
  ]
  
  return(dt)
}